-- Step 1: Just create the table with NO constraints
-- Copy and paste this SINGLE statement

CREATE TABLE substance_use_assessments (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    patient_id UUID,
    hospital_id UUID,
    encounter_id UUID,
    admission_id UUID,
    status TEXT DEFAULT 'in_progress',
    assessed_by UUID,
    reviewed_by UUID,
    assessment_date TIMESTAMPTZ DEFAULT NOW(),
    primary_substance TEXT,
    demographics JSONB DEFAULT '{}',
    social_factors JSONB DEFAULT '{}',
    legal_status JSONB,
    previous_detox_attempts JSONB DEFAULT '[]',
    psychiatric_history JSONB DEFAULT '{}',
    substances JSONB DEFAULT '[]',
    addiction_severity_score JSONB,
    withdrawal_prediction JSONB,
    pain_management JSONB,
    comorbidity_modifications JSONB DEFAULT '[]',
    care_setting_decision JSONB,
    consent_document JSONB,
    patient_info_leaflet JSONB,
    monitoring_records JSONB DEFAULT '[]',
    follow_up_schedule JSONB DEFAULT '[]',
    exclusion_criteria JSONB DEFAULT '{}',
    audit_log JSONB DEFAULT '[]',
    clinical_summary TEXT,
    next_review_date TIMESTAMPTZ,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    updated_at TIMESTAMPTZ DEFAULT NOW(),
    completed_at TIMESTAMPTZ,
    completed_by UUID,
    synced_at TIMESTAMPTZ,
    local_id TEXT
);
