-- Part 1: Create the substance_use_assessments table
-- Run this first

CREATE TABLE IF NOT EXISTS substance_use_assessments (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    patient_id UUID NOT NULL REFERENCES patients(id) ON DELETE CASCADE,
    hospital_id UUID NOT NULL REFERENCES hospitals(id) ON DELETE CASCADE,
    encounter_id UUID REFERENCES encounters(id) ON DELETE SET NULL,
    admission_id UUID REFERENCES admissions(id) ON DELETE SET NULL,
    status TEXT NOT NULL DEFAULT 'in_progress' CHECK (status IN ('in_progress', 'completed', 'reviewed', 'archived')),
    assessed_by UUID NOT NULL REFERENCES users(id),
    reviewed_by UUID REFERENCES users(id),
    assessment_date TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    primary_substance TEXT NOT NULL,
    demographics JSONB NOT NULL DEFAULT '{}'::jsonb,
    social_factors JSONB NOT NULL DEFAULT '{}'::jsonb,
    legal_status JSONB DEFAULT NULL,
    previous_detox_attempts JSONB NOT NULL DEFAULT '[]'::jsonb,
    psychiatric_history JSONB NOT NULL DEFAULT '{}'::jsonb,
    substances JSONB NOT NULL DEFAULT '[]'::jsonb,
    addiction_severity_score JSONB DEFAULT NULL,
    withdrawal_prediction JSONB DEFAULT NULL,
    pain_management JSONB DEFAULT NULL,
    comorbidity_modifications JSONB NOT NULL DEFAULT '[]'::jsonb,
    care_setting_decision JSONB DEFAULT NULL,
    consent_document JSONB DEFAULT NULL,
    patient_info_leaflet JSONB DEFAULT NULL,
    monitoring_records JSONB NOT NULL DEFAULT '[]'::jsonb,
    follow_up_schedule JSONB NOT NULL DEFAULT '[]'::jsonb,
    exclusion_criteria JSONB NOT NULL DEFAULT '{}'::jsonb,
    audit_log JSONB NOT NULL DEFAULT '[]'::jsonb,
    clinical_summary TEXT,
    next_review_date TIMESTAMPTZ,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    completed_at TIMESTAMPTZ,
    completed_by UUID REFERENCES users(id),
    synced_at TIMESTAMPTZ,
    local_id TEXT
);
