-- Minimal table creation - no foreign keys
-- Run this first to test connection

CREATE TABLE IF NOT EXISTS substance_use_assessments (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    patient_id UUID NOT NULL,
    hospital_id UUID NOT NULL,
    encounter_id UUID,
    admission_id UUID,
    status TEXT NOT NULL DEFAULT 'in_progress',
    assessed_by UUID NOT NULL,
    reviewed_by UUID,
    assessment_date TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    primary_substance TEXT NOT NULL,
    demographics JSONB DEFAULT '{}'::jsonb,
    social_factors JSONB DEFAULT '{}'::jsonb,
    legal_status JSONB,
    previous_detox_attempts JSONB DEFAULT '[]'::jsonb,
    psychiatric_history JSONB DEFAULT '{}'::jsonb,
    substances JSONB DEFAULT '[]'::jsonb,
    addiction_severity_score JSONB,
    withdrawal_prediction JSONB,
    pain_management JSONB,
    comorbidity_modifications JSONB DEFAULT '[]'::jsonb,
    care_setting_decision JSONB,
    consent_document JSONB,
    patient_info_leaflet JSONB,
    monitoring_records JSONB DEFAULT '[]'::jsonb,
    follow_up_schedule JSONB DEFAULT '[]'::jsonb,
    exclusion_criteria JSONB DEFAULT '{}'::jsonb,
    audit_log JSONB DEFAULT '[]'::jsonb,
    clinical_summary TEXT,
    next_review_date TIMESTAMPTZ,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    updated_at TIMESTAMPTZ DEFAULT NOW(),
    completed_at TIMESTAMPTZ,
    completed_by UUID,
    synced_at TIMESTAMPTZ,
    local_id TEXT
);
