/**
 * PDF Generator for External Reviews
 * AstroHEALTH Innovations in Healthcare
 */

import jsPDF from 'jspdf';
import autoTable from 'jspdf-autotable';
import { format, parseISO } from 'date-fns';
import type { ExternalReview } from '../../../types';

interface ExportOptions {
  dateFrom?: string;
  dateTo?: string;
  hospitalName?: string;
  generatedBy: string;
}

export async function generateExternalReviewPDF(
  reviews: ExternalReview[],
  options: ExportOptions
): Promise<Blob> {
  const doc = new jsPDF();
  
  // Colors
  const primaryColor: [number, number, number] = [79, 70, 229]; // Indigo
  const grayColor: [number, number, number] = [107, 114, 128];
  
  // Header
  doc.setFillColor(primaryColor[0], primaryColor[1], primaryColor[2]);
  doc.rect(0, 0, 210, 40, 'F');
  
  doc.setTextColor(255, 255, 255);
  doc.setFontSize(14);
  doc.setFont('helvetica', 'bold');
  doc.text('DR NNADI-BURNS, PLASTIC AND RECONSTRUCTIVE SURGERY SERVICES', 14, 25);
  
  // Date and filters info
  doc.setTextColor(grayColor[0], grayColor[1], grayColor[2]);
  doc.setFontSize(10);
  
  let yPos = 50;
  
  doc.text(`Generated: ${format(new Date(), 'dd MMM yyyy, HH:mm')}`, 14, yPos);
  yPos += 6;
  
  doc.text(`Generated By: ${options.generatedBy}`, 14, yPos);
  yPos += 6;
  
  if (options.dateFrom || options.dateTo) {
    const fromDate = options.dateFrom ? format(parseISO(options.dateFrom), 'dd MMM yyyy') : 'Start';
    const toDate = options.dateTo ? format(parseISO(options.dateTo), 'dd MMM yyyy') : 'Present';
    doc.text(`Period: ${fromDate} - ${toDate}`, 14, yPos);
    yPos += 6;
  }
  
  if (options.hospitalName) {
    doc.text(`Hospital: ${options.hospitalName}`, 14, yPos);
    yPos += 6;
  }
  
  // Summary stats
  yPos += 4;
  doc.setFillColor(243, 244, 246);
  doc.roundedRect(14, yPos, 182, 20, 3, 3, 'F');
  
  doc.setTextColor(0, 0, 0);
  doc.setFontSize(11);
  doc.setFont('helvetica', 'bold');
  
  const totalFees = reviews.reduce((sum, r) => sum + r.fee, 0);
  
  doc.text(`Total Reviews: ${reviews.length}`, 20, yPos + 8);
  doc.text(`Total Fees: ₦${totalFees.toLocaleString()}`, 100, yPos + 8);
  
  yPos += 30;
  
  // Table
  const tableData = reviews.map((review, index) => [
    (index + 1).toString(),
    review.patientName,
    review.hospitalName.length > 20 ? review.hospitalName.substring(0, 20) + '...' : review.hospitalName,
    review.folderNumber,
    review.servicesRendered.length > 30 ? review.servicesRendered.substring(0, 30) + '...' : review.servicesRendered,
    `₦${review.fee.toLocaleString()}`,
    format(parseISO(review.serviceDate), 'dd/MM/yyyy'),
  ]);
  
  autoTable(doc, {
    startY: yPos,
    head: [['#', 'Patient', 'Hospital', 'Folder', 'Services', 'Fee', 'Date']],
    body: tableData,
    theme: 'grid',
    headStyles: {
      fillColor: primaryColor,
      textColor: [255, 255, 255],
      fontStyle: 'bold',
      fontSize: 9,
    },
    bodyStyles: {
      fontSize: 8,
      textColor: [0, 0, 0],
    },
    alternateRowStyles: {
      fillColor: [249, 250, 251],
    },
    columnStyles: {
      0: { cellWidth: 10 },
      1: { cellWidth: 35 },
      2: { cellWidth: 35 },
      3: { cellWidth: 20 },
      4: { cellWidth: 45 },
      5: { cellWidth: 25 },
      6: { cellWidth: 22 },
    },
    margin: { left: 14, right: 14 },
  });
  
  // Footer
  const pageCount = doc.getNumberOfPages();
  for (let i = 1; i <= pageCount; i++) {
    doc.setPage(i);
    doc.setFontSize(8);
    doc.setTextColor(grayColor[0], grayColor[1], grayColor[2]);
    doc.text(
      `Page ${i} of ${pageCount}`,
      doc.internal.pageSize.getWidth() / 2,
      doc.internal.pageSize.getHeight() - 10,
      { align: 'center' }
    );
    doc.text(
      'AstroHEALTH - Healthcare Management System',
      14,
      doc.internal.pageSize.getHeight() - 10
    );
  }
  
  return doc.output('blob');
}
