/**
 * PDF Generator for External Reviews
 * Dr Nnadi-Burns, Plastic and Reconstructive Surgery Services
 */

import jsPDF from 'jspdf';
import autoTable from 'jspdf-autotable';
import { format, parseISO } from 'date-fns';
import type { ExternalReview } from '../../../types';

interface ExportOptions {
  dateFrom?: string;
  dateTo?: string;
  hospitalName?: string;
  generatedBy: string;
}

// Format currency with NGN prefix (avoiding special character issues)
function formatCurrency(amount: number): string {
  return 'NGN ' + amount.toLocaleString('en-NG');
}

export async function generateExternalReviewPDF(
  reviews: ExternalReview[],
  options: ExportOptions
): Promise<Blob> {
  const doc = new jsPDF();
  
  // Use Times font (closest to Georgia available in jsPDF)
  const fontName = 'times';
  
  // Colors
  const primaryColor: [number, number, number] = [0, 51, 102]; // Dark blue - more professional
  const grayColor: [number, number, number] = [80, 80, 80];
  
  // Header
  doc.setFillColor(primaryColor[0], primaryColor[1], primaryColor[2]);
  doc.rect(0, 0, 210, 35, 'F');
  
  doc.setTextColor(255, 255, 255);
  doc.setFontSize(16);
  doc.setFont(fontName, 'bold');
  doc.text('DR NNADI-BURNS', 105, 15, { align: 'center' });
  
  doc.setFontSize(11);
  doc.setFont(fontName, 'normal');
  doc.text('PLASTIC AND RECONSTRUCTIVE SURGERY SERVICES', 105, 25, { align: 'center' });
  
  // Report title
  doc.setTextColor(primaryColor[0], primaryColor[1], primaryColor[2]);
  doc.setFontSize(14);
  doc.setFont(fontName, 'bold');
  doc.text('EXTERNAL REVIEW REPORT', 105, 45, { align: 'center' });
  
  // Horizontal line under title
  doc.setDrawColor(primaryColor[0], primaryColor[1], primaryColor[2]);
  doc.setLineWidth(0.5);
  doc.line(14, 50, 196, 50);
  
  // Date and filters info
  doc.setTextColor(grayColor[0], grayColor[1], grayColor[2]);
  doc.setFontSize(10);
  doc.setFont(fontName, 'normal');
  
  let yPos = 58;
  
  doc.text('Generated: ' + format(new Date(), 'dd MMM yyyy, HH:mm'), 14, yPos);
  yPos += 7;
  
  doc.text('Generated By: ' + options.generatedBy, 14, yPos);
  yPos += 7;
  
  if (options.dateFrom || options.dateTo) {
    const fromDate = options.dateFrom ? format(parseISO(options.dateFrom), 'dd MMM yyyy') : 'Start';
    const toDate = options.dateTo ? format(parseISO(options.dateTo), 'dd MMM yyyy') : 'Present';
    doc.text('Period: ' + fromDate + ' - ' + toDate, 14, yPos);
    yPos += 7;
  }
  
  if (options.hospitalName) {
    doc.text('Hospital: ' + options.hospitalName, 14, yPos);
    yPos += 7;
  }
  
  // Summary stats box
  yPos += 5;
  doc.setFillColor(240, 240, 245);
  doc.setDrawColor(primaryColor[0], primaryColor[1], primaryColor[2]);
  doc.setLineWidth(0.3);
  doc.roundedRect(14, yPos, 182, 18, 2, 2, 'FD');
  
  doc.setTextColor(primaryColor[0], primaryColor[1], primaryColor[2]);
  doc.setFontSize(11);
  doc.setFont(fontName, 'bold');
  
  const totalFees = reviews.reduce((sum, r) => sum + r.fee, 0);
  
  doc.text('Total Reviews: ' + reviews.length, 24, yPos + 11);
  doc.text('Total Fees: ' + formatCurrency(totalFees), 110, yPos + 11);
  
  yPos += 28;
  
  // Table
  const tableData = reviews.map((review, index) => [
    (index + 1).toString(),
    review.patientName,
    review.hospitalName.length > 25 ? review.hospitalName.substring(0, 25) + '...' : review.hospitalName,
    review.folderNumber,
    review.servicesRendered.length > 35 ? review.servicesRendered.substring(0, 35) + '...' : review.servicesRendered,
    formatCurrency(review.fee),
    format(parseISO(review.serviceDate), 'dd/MM/yyyy'),
  ]);
  
  autoTable(doc, {
    startY: yPos,
    head: [['#', 'Patient Name', 'Hospital', 'Folder No.', 'Services Rendered', 'Fee', 'Date']],
    body: tableData,
    theme: 'grid',
    styles: {
      font: fontName,
      fontSize: 9,
      cellPadding: 3,
    },
    headStyles: {
      fillColor: primaryColor,
      textColor: [255, 255, 255],
      fontStyle: 'bold',
      fontSize: 9,
      halign: 'center',
    },
    bodyStyles: {
      fontSize: 9,
      textColor: [40, 40, 40],
    },
    alternateRowStyles: {
      fillColor: [248, 248, 252],
    },
    columnStyles: {
      0: { cellWidth: 10, halign: 'center' },
      1: { cellWidth: 32 },
      2: { cellWidth: 32 },
      3: { cellWidth: 20, halign: 'center' },
      4: { cellWidth: 45 },
      5: { cellWidth: 28, halign: 'right' },
      6: { cellWidth: 22, halign: 'center' },
    },
    margin: { left: 14, right: 14 },
  });
  
  // Footer on all pages
  const pageCount = doc.getNumberOfPages();
  for (let i = 1; i <= pageCount; i++) {
    doc.setPage(i);
    
    // Footer line
    doc.setDrawColor(primaryColor[0], primaryColor[1], primaryColor[2]);
    doc.setLineWidth(0.3);
    doc.line(14, doc.internal.pageSize.getHeight() - 18, 196, doc.internal.pageSize.getHeight() - 18);
    
    doc.setFontSize(9);
    doc.setFont(fontName, 'normal');
    doc.setTextColor(grayColor[0], grayColor[1], grayColor[2]);
    doc.text(
      'Page ' + i + ' of ' + pageCount,
      doc.internal.pageSize.getWidth() / 2,
      doc.internal.pageSize.getHeight() - 10,
      { align: 'center' }
    );
    doc.text(
      'Dr Nnadi-Burns - Plastic and Reconstructive Surgery',
      14,
      doc.internal.pageSize.getHeight() - 10
    );
  }
  
  return doc.output('blob');
}
