/**
 * PDF Generator for External Reviews
 * Dr Nnadi-Burns, Plastic and Reconstructive Surgery Services
 * 
 * Standards: Georgia font (Times), 10pt, 0.5 line spacing, 0.5" margins, 2 columns
 */

import jsPDF from 'jspdf';
import autoTable from 'jspdf-autotable';
import { format, parseISO } from 'date-fns';
import type { ExternalReview } from '../../../types';
import { 
  PDF_MARGINS, 
  PDF_FONTS, 
  PDF_FONT_SIZES, 
  PDF_COLORS, 
  PDF_LINE_HEIGHT,
  ensureWhiteBackground 
} from '../../../utils/pdfConfig';

interface ExportOptions {
  dateFrom?: string;
  dateTo?: string;
  hospitalName?: string;
  generatedBy: string;
}

// Format currency with NGN prefix (avoiding special character issues)
function formatCurrency(amount: number): string {
  return 'NGN ' + amount.toLocaleString('en-NG');
}

export async function generateExternalReviewPDF(
  reviews: ExternalReview[],
  options: ExportOptions
): Promise<Blob> {
  const doc = new jsPDF({
    orientation: 'portrait',
    unit: 'mm',
    format: 'a4',
  });
  
  // Ensure white background
  ensureWhiteBackground(doc);
  
  // Use Times font (closest to Georgia available in jsPDF)
  const fontName = PDF_FONTS.primary;
  
  // Colors - deep black text on white background
  const primaryColor: [number, number, number] = [0, 0, 0]; // Deep black for captions
  const textColor: [number, number, number] = [0, 0, 0]; // Deep black for all text
  
  // Header - white background, black text
  doc.setTextColor(0, 0, 0);
  doc.setFontSize(14);
  doc.setFont(fontName, 'bold');
  doc.text('DR NNADI-BURNS', 105, PDF_MARGINS.top, { align: 'center' });
  
  doc.setFontSize(10);
  doc.setFont(fontName, 'bold');
  doc.text('PLASTIC AND RECONSTRUCTIVE SURGERY SERVICES', 105, PDF_MARGINS.top + 6, { align: 'center' });
  
  // Report title
  doc.setFontSize(12);
  doc.setFont(fontName, 'bold');
  doc.text('EXTERNAL REVIEW REPORT', 105, PDF_MARGINS.top + 16, { align: 'center' });
  
  // Horizontal line under title
  doc.setDrawColor(0, 0, 0);
  doc.setLineWidth(0.5);
  doc.line(PDF_MARGINS.left, PDF_MARGINS.top + 20, 210 - PDF_MARGINS.right, PDF_MARGINS.top + 20);
  
  // Two-column layout for metadata
  const colWidth = (210 - PDF_MARGINS.left - PDF_MARGINS.right - 6) / 2; // 6mm gutter
  const col1X = PDF_MARGINS.left;
  const col2X = PDF_MARGINS.left + colWidth + 6;
  
  let yPos = PDF_MARGINS.top + 28;
  const lineHeight = PDF_FONT_SIZES.body * PDF_LINE_HEIGHT.tight * 0.3528;
  
  // Left column - Report info
  doc.setFontSize(PDF_FONT_SIZES.body);
  doc.setFont(fontName, 'bold');
  doc.setTextColor(0, 0, 0);
  doc.text('Report Information:', col1X, yPos);
  yPos += lineHeight + 1;
  
  doc.setFont(fontName, 'normal');
  doc.text('Generated: ' + format(new Date(), 'dd MMM yyyy, HH:mm'), col1X, yPos);
  yPos += lineHeight;
  doc.text('Generated By: ' + options.generatedBy, col1X, yPos);
  yPos += lineHeight;
  
  if (options.dateFrom || options.dateTo) {
    const fromDate = options.dateFrom ? format(parseISO(options.dateFrom), 'dd MMM yyyy') : 'Start';
    const toDate = options.dateTo ? format(parseISO(options.dateTo), 'dd MMM yyyy') : 'Present';
    doc.text('Period: ' + fromDate + ' - ' + toDate, col1X, yPos);
    yPos += lineHeight;
  }
  
  if (options.hospitalName) {
    doc.text('Hospital: ' + options.hospitalName, col1X, yPos);
    yPos += lineHeight;
  }
  
  // Right column - Summary stats
  const statsY = PDF_MARGINS.top + 28;
  doc.setFont(fontName, 'bold');
  doc.text('Summary:', col2X, statsY);
  
  const totalFees = reviews.reduce((sum, r) => sum + r.fee, 0);
  
  doc.setFont(fontName, 'normal');
  doc.text('Total Reviews: ' + reviews.length, col2X, statsY + lineHeight + 1);
  doc.text('Total Fees: ' + formatCurrency(totalFees), col2X, statsY + (lineHeight * 2) + 1);
  
  yPos = Math.max(yPos, statsY + (lineHeight * 3)) + 8;
  
  // Table
  const tableData = reviews.map((review, index) => [
    (index + 1).toString(),
    review.patientName,
    review.hospitalName.length > 25 ? review.hospitalName.substring(0, 25) + '...' : review.hospitalName,
    review.folderNumber,
    review.servicesRendered.length > 35 ? review.servicesRendered.substring(0, 35) + '...' : review.servicesRendered,
    formatCurrency(review.fee),
    format(parseISO(review.serviceDate), 'dd/MM/yyyy'),
  ]);
  
  autoTable(doc, {
    startY: yPos,
    head: [['#', 'Patient Name', 'Hospital', 'Folder No.', 'Services Rendered', 'Fee', 'Date']],
    body: tableData,
    theme: 'grid',
    styles: {
      font: fontName,
      fontSize: PDF_FONT_SIZES.body, // 10pt
      cellPadding: 2,
      lineColor: [0, 0, 0],
      lineWidth: 0.2,
      textColor: [0, 0, 0], // Deep black
    },
    headStyles: {
      fillColor: [255, 255, 255], // White background
      textColor: [0, 0, 0], // Deep black
      fontStyle: 'bold',
      fontSize: PDF_FONT_SIZES.body,
      halign: 'center',
    },
    bodyStyles: {
      fontSize: PDF_FONT_SIZES.body,
      textColor: [0, 0, 0], // Deep black
      fillColor: [255, 255, 255], // White background
    },
    alternateRowStyles: {
      fillColor: [255, 255, 255], // White background (no alternating)
    },
    columnStyles: {
      0: { cellWidth: 10, halign: 'center' },
      1: { cellWidth: 32 },
      2: { cellWidth: 32 },
      3: { cellWidth: 20, halign: 'center' },
      4: { cellWidth: 45 },
      5: { cellWidth: 28, halign: 'right' },
      6: { cellWidth: 22, halign: 'center' },
    },
    margin: { left: PDF_MARGINS.left, right: PDF_MARGINS.right },
  });
  
  // Footer on all pages
  const pageCount = doc.getNumberOfPages();
  for (let i = 1; i <= pageCount; i++) {
    doc.setPage(i);
    ensureWhiteBackground(doc);
    
    // Footer line
    doc.setDrawColor(0, 0, 0);
    doc.setLineWidth(0.3);
    doc.line(PDF_MARGINS.left, doc.internal.pageSize.getHeight() - 15, 210 - PDF_MARGINS.right, doc.internal.pageSize.getHeight() - 15);
    
    doc.setFontSize(PDF_FONT_SIZES.body);
    doc.setFont(fontName, 'normal');
    doc.setTextColor(0, 0, 0);
    doc.text(
      'Page ' + i + ' of ' + pageCount,
      doc.internal.pageSize.getWidth() / 2,
      doc.internal.pageSize.getHeight() - 8,
      { align: 'center' }
    );
    doc.text(
      'Dr Nnadi-Burns - Plastic and Reconstructive Surgery',
      PDF_MARGINS.left,
      doc.internal.pageSize.getHeight() - 8
    );
  }
  
  return doc.output('blob');
}
