/**
 * Burns Educational Content - Part 3
 * Friction Burns, Radiation Burns, Inhalation Injury, Burn Contractures
 * Category A - Patient Education Module
 * AstroHEALTH Innovations in Healthcare
 */

import type { EducationCondition } from '../types';

export const burnsEducationPart3: EducationCondition[] = [
  // A5. Friction Burns (Road Rash)
  {
    id: 'burns-friction',
    categoryId: 'A',
    name: 'Friction Burns (Road Rash)',
    alternateNames: ['Abrasion burns', 'Road rash', 'Tarmac burns', 'Rug burns'],
    icdCode: 'T24.3',
    
    overview: {
      definition: 'Friction burns occur when skin is rapidly rubbed against a rough surface, combining abrasive injury with heat generated by friction. Common in road traffic accidents, sports injuries, and falls. These injuries involve both tissue loss from abrasion and thermal damage from friction heat.',
      causes: [
        'Motorcycle and bicycle accidents',
        'Falls from moving vehicles',
        'Sports injuries (artificial turf, running tracks)',
        'Playground injuries',
        'Rope burns',
        'Treadmill accidents',
        'Falls on rough surfaces'
      ],
      riskFactors: [
        'Motorcycle riding without protective gear',
        'Contact sports',
        'Working with ropes or moving machinery',
        'Cycling without protective clothing',
        'Children at play'
      ],
      symptoms: [
        'Immediate burning pain',
        'Raw, red, weeping wound surface',
        'Skin loss of varying depth',
        'Embedded debris (gravel, dirt)',
        'Bleeding',
        'Swelling around wound'
      ],
      diagnosis: [
        'Clinical examination',
        'Assessment of wound depth',
        'Check for embedded debris',
        'Assess for associated injuries (fractures, head injury)',
        'Tetanus status review'
      ],
      classification: [
        {
          name: 'Depth Classification',
          description: 'Similar to burn depth classification',
          grades: [
            { grade: 'Superficial', description: 'Epidermis only', characteristics: ['Red, painful', 'Heals 1-2 weeks'] },
            { grade: 'Partial Thickness', description: 'Into dermis', characteristics: ['Raw, weeping', 'Heals 2-4 weeks', 'May scar'] },
            { grade: 'Full Thickness', description: 'All skin layers', characteristics: ['Tissue loss', 'Needs grafting'] }
          ]
        }
      ],
      epidemiology: 'Very common, especially in younger populations involved in road traffic or sports. Often associated with other traumatic injuries.',
      prognosis: 'Most friction burns are superficial or partial thickness and heal well. Deep injuries may require grafting and can result in significant scarring.'
    },
    
    treatmentPhases: [
      {
        phase: 1,
        name: 'Initial Treatment (0-48 hours)',
        duration: '0-48 hours',
        description: 'Wound cleaning, debris removal, and assessment.',
        goals: [
          'Thoroughly clean wound',
          'Remove all embedded debris',
          'Assess wound depth',
          'Tetanus prophylaxis',
          'Pain control'
        ],
        interventions: [
          'Copious irrigation with saline or water',
          'Scrubbing to remove embedded material (with anesthesia if extensive)',
          'Application of non-adherent dressing',
          'Tetanus toxoid if needed',
          'Analgesia'
        ],
        milestones: [
          'All debris removed',
          'Wound thoroughly cleaned',
          'Pain controlled'
        ],
        nursingCare: [
          'Assess for associated injuries',
          'Thorough wound cleaning',
          'Appropriate dressing application',
          'Pain management'
        ]
      },
      {
        phase: 2,
        name: 'Healing Phase (2 days - 4 weeks)',
        duration: '2 days to 4 weeks',
        description: 'Wound healing and infection prevention.',
        goals: [
          'Promote wound healing',
          'Prevent infection',
          'Monitor for healing progress'
        ],
        interventions: [
          'Regular dressing changes',
          'Moist wound healing environment',
          'Watch for signs of infection',
          'Skin grafting if full thickness injury'
        ],
        milestones: [
          'Progressive wound healing',
          'No infection',
          'Complete epithelialization'
        ]
      },
      {
        phase: 3,
        name: 'Scar Management (4 weeks onwards)',
        duration: '4 weeks to 1 year',
        description: 'Minimize scarring and restore function.',
        goals: [
          'Minimize scar formation',
          'Restore function',
          'Address cosmetic concerns'
        ],
        interventions: [
          'Silicone gel therapy',
          'Massage therapy',
          'Sun protection',
          'Scar revision if needed'
        ],
        milestones: [
          'Scar maturation',
          'Satisfactory appearance'
        ]
      }
    ],
    
    preoperativeInstructions: {
      consultations: ['Surgical assessment if deep wounds'],
      investigations: ['Blood tests if surgery needed', 'X-rays for associated injuries'],
      medications: [
        { medication: 'Blood thinners', instruction: 'discuss', timing: 'Before surgery', reason: 'Bleeding risk' }
      ],
      dietaryRestrictions: ['Nil by mouth if surgery planned'],
      physicalPreparation: ['Wound cleaning if not already done'],
      psychologicalPreparation: ['Explain procedure and expected outcomes'],
      consentRequirements: ['Debridement and grafting consent if applicable'],
      dayBeforeSurgery: ['Fasting instructions'],
      dayOfSurgery: ['Fasting', 'Arrive as scheduled']
    },
    
    intraoperativeInfo: {
      anesthesiaType: ['Local anesthesia for small areas', 'Regional or general for extensive wounds'],
      procedureDescription: 'Thorough debridement and cleaning under anesthesia, followed by skin grafting if full thickness injury.',
      procedureSteps: [
        'Wound irrigation',
        'Debridement of non-viable tissue',
        'Removal of all foreign material',
        'Skin grafting if needed',
        'Dressing application'
      ],
      duration: '30 minutes to 2 hours',
      techniques: ['Debridement', 'Split-thickness skin grafting if needed'],
      expectedBloodLoss: 'Minimal to moderate',
      possibleComplications: ['Infection', 'Graft failure', 'Scarring', 'Retained foreign body']
    },
    
    postoperativeInstructions: {
      immediatePostop: {
        monitoring: ['Pain levels', 'Wound observation'],
        positioning: 'Elevate affected area',
        fluidManagement: 'Normal oral intake',
        painControl: 'Oral analgesia',
        expectedSymptoms: ['Pain', 'Mild swelling'],
        nursingInstructions: ['Keep dressing dry', 'Monitor for infection']
      },
      woundCare: [
        { day: 'Days 1-3', instruction: 'Keep dressing clean and dry', frequency: 'Check daily' },
        { day: 'Days 3-7', instruction: 'First dressing change by healthcare provider', frequency: 'As scheduled' },
        { day: 'Weeks 1-3', instruction: 'Continue wound care until healed', frequency: 'Every 2-3 days' }
      ],
      painManagement: {
        expectedPainLevel: 'Moderate initially',
        medications: ['Paracetamol', 'Ibuprofen'],
        nonPharmacological: ['Elevation', 'Cooling'],
        whenToSeekHelp: 'Increasing pain, spreading redness, fever'
      },
      activityRestrictions: [
        { activity: 'Use of affected area', restriction: 'Limited', duration: 'Until healed', reason: 'Wound protection' }
      ],
      dietaryGuidelines: ['Normal healthy diet', 'Adequate protein for healing'],
      medicationRegimen: [
        { name: 'Paracetamol', dose: '1g', frequency: 'Every 6 hours PRN', purpose: 'Pain relief' }
      ],
      physicalTherapy: {
        startTiming: 'After wound heals',
        frequency: 'As needed',
        exercises: [{ name: 'Range of motion', description: 'Gentle stretching', frequency: 'Daily' }],
        precautions: ['Avoid stretching open wounds'],
        goals: ['Maintain flexibility', 'Prevent stiffness']
      },
      returnToWork: '1-2 weeks for desk work; longer for physical work',
      returnToNormalActivities: '2-4 weeks depending on severity'
    },
    
    expectedOutcomes: {
      shortTerm: [
        { timeframe: '2-4 weeks', expectation: 'Wound healing', indicators: ['Complete epithelialization', 'No infection'] }
      ],
      longTerm: [
        { timeframe: '6-12 months', expectation: 'Scar maturation', indicators: ['Soft scar', 'Color normalizing'] }
      ],
      functionalRecovery: 'Usually complete recovery',
      cosmeticOutcome: 'Variable scarring depending on depth and location',
      qualityOfLife: 'Generally excellent',
      possibleComplications: [
        { complication: 'Infection', riskLevel: 'moderate', prevention: 'Thorough cleaning, proper wound care', management: 'Antibiotics' },
        { complication: 'Tattooing', riskLevel: 'moderate', prevention: 'Complete debris removal', management: 'Dermabrasion if permanent' }
      ],
      successRate: 'Excellent for superficial injuries; good for deeper wounds with proper treatment'
    },
    
    followUpCare: {
      schedule: [
        { timing: '1 week', purpose: 'Wound check', whatToExpect: 'Dressing change, healing assessment' },
        { timing: '2-3 weeks', purpose: 'Confirm healing', whatToExpect: 'Start scar management if healed' }
      ],
      ongoingMonitoring: ['Scar progression'],
      rehabilitationNeeds: ['Usually minimal'],
      supportServices: ['Scar management education'],
      longTermConsiderations: ['Sun protection of healed areas', 'Scar revision if needed']
    },
    
    complianceRequirements: [
      { requirement: 'Keep wound clean', importance: 'critical', consequence: 'Infection', tips: ['Follow dressing instructions'] },
      { requirement: 'Attend follow-up', importance: 'important', consequence: 'Missed complications', tips: ['Keep appointments'] }
    ],
    
    whoGuidelines: [
      {
        title: 'WHO Wound Care Guidelines',
        reference: 'WHO Wound Management',
        keyPoints: ['Thorough cleaning essential', 'Remove all foreign material', 'Keep wounds moist for healing']
      }
    ],
    
    warningSigns: ['Increasing pain', 'Redness spreading', 'Pus discharge', 'Fever'],
    emergencySigns: ['High fever', 'Red streaks from wound', 'Severe swelling']
  },

  // A6. Inhalation Injury
  {
    id: 'burns-inhalation',
    categoryId: 'A',
    name: 'Inhalation Injury',
    alternateNames: ['Smoke inhalation', 'Airway burn', 'Pulmonary burn injury'],
    icdCode: 'T27',
    
    overview: {
      definition: 'Inhalation injury refers to damage to the respiratory tract from inhaling hot gases, smoke, or toxic products of combustion. It is a major cause of mortality in fire victims and significantly worsens the prognosis of patients with cutaneous burns. Can affect the upper airway (heat injury), lower airways (chemical injury), and cause systemic toxicity (carbon monoxide, cyanide).',
      causes: [
        'House fires',
        'Industrial fires',
        'Vehicle fires',
        'Enclosed space fires',
        'Steam inhalation accidents',
        'Chemical fires with toxic fumes'
      ],
      riskFactors: [
        'Trapped in enclosed space with fire',
        'Loss of consciousness in fire',
        'Fires involving plastics (release cyanide)',
        'Delay in rescue',
        'Pre-existing respiratory disease'
      ],
      symptoms: [
        'Hoarse voice or stridor',
        'Cough with carbonaceous (black) sputum',
        'Facial burns, singed eyebrows/nasal hairs',
        'Soot in mouth or nose',
        'Wheezing or respiratory distress',
        'Difficulty swallowing',
        'Confusion (carbon monoxide poisoning)',
        'Pink skin color (carbon monoxide)',
        'Cherry red lips (cyanide)'
      ],
      diagnosis: [
        'Clinical suspicion based on mechanism',
        'Direct laryngoscopy to visualize upper airway',
        'Bronchoscopy - gold standard for diagnosis',
        'Arterial blood gas including carboxyhemoglobin',
        'Chest X-ray (may be normal initially)',
        'Blood lactate level (elevated in cyanide poisoning)'
      ],
      classification: [
        {
          name: 'Anatomic Classification',
          description: 'Based on area of airway affected',
          grades: [
            { grade: 'Upper Airway', description: 'Above vocal cords', characteristics: ['Direct thermal injury', 'Edema and obstruction risk', 'Visible on laryngoscopy'] },
            { grade: 'Lower Airway', description: 'Tracheobronchial tree', characteristics: ['Chemical injury from smoke', 'Bronchospasm', 'Seen on bronchoscopy'] },
            { grade: 'Parenchymal', description: 'Lung tissue', characteristics: ['Inflammatory response', 'ARDS risk', 'May develop over days'] },
            { grade: 'Systemic', description: 'Toxic gas absorption', characteristics: ['CO and cyanide poisoning', 'Affects oxygen delivery', 'Can be fatal'] }
          ]
        }
      ],
      epidemiology: 'Present in 10-20% of burn admissions but accounts for 60-80% of fire-related deaths. Significantly increases mortality when combined with cutaneous burns.',
      prognosis: 'Adds 20% mortality to burns of similar size without inhalation injury. Survivors may have long-term pulmonary complications. Early intubation improves outcomes.'
    },
    
    treatmentPhases: [
      {
        phase: 1,
        name: 'Emergency Phase (0-72 hours)',
        duration: '0-72 hours',
        description: 'Secure airway, treat toxicity, provide respiratory support.',
        goals: [
          'Secure airway before edema develops',
          'Treat carbon monoxide and cyanide poisoning',
          'Provide respiratory support',
          'Monitor for deterioration'
        ],
        interventions: [
          'High-flow 100% oxygen (treats CO poisoning)',
          'Early endotracheal intubation if airway threatened',
          'Bronchoscopy for diagnosis and therapeutic suctioning',
          'Hydroxocobalamin for suspected cyanide poisoning',
          'Nebulized bronchodilators',
          'Chest physiotherapy',
          'Mechanical ventilation if respiratory failure'
        ],
        milestones: [
          'Airway secured',
          'CO levels declining',
          'Adequate oxygenation',
          'No progressive airway obstruction'
        ],
        nursingCare: [
          'Continuous SpO2 monitoring',
          'Frequent respiratory assessment',
          'Suctioning as needed',
          'Head of bed elevation',
          'Monitor for increasing stridor or work of breathing'
        ]
      },
      {
        phase: 2,
        name: 'Pulmonary Management Phase (3-14 days)',
        duration: '3-14 days',
        description: 'Prevent and manage respiratory complications.',
        goals: [
          'Wean from mechanical ventilation',
          'Prevent pneumonia',
          'Clear secretions',
          'Support lung healing'
        ],
        interventions: [
          'Lung-protective ventilation strategies',
          'Aggressive pulmonary toilet',
          'Early tracheostomy if prolonged ventilation expected',
          'Bronchoscopy for secretion clearance',
          'Antibiotics for pneumonia',
          'Early mobility when safe'
        ],
        milestones: [
          'Successful extubation',
          'No ventilator-associated pneumonia',
          'Clearing secretions',
          'Improving lung function'
        ]
      },
      {
        phase: 3,
        name: 'Recovery Phase (2 weeks onwards)',
        duration: '2 weeks to months',
        description: 'Pulmonary rehabilitation and recovery.',
        goals: [
          'Optimize lung function',
          'Rehabilitation',
          'Address long-term complications'
        ],
        interventions: [
          'Pulmonary function testing',
          'Respiratory rehabilitation',
          'Treatment of reactive airways disease',
          'Ongoing monitoring'
        ],
        milestones: [
          'Return to baseline function',
          'Independence in activities',
          'Stable respiratory status'
        ]
      }
    ],
    
    preoperativeInstructions: {
      consultations: ['Pulmonology', 'Anesthesia for airway management', 'Critical care'],
      investigations: ['Arterial blood gas', 'Carboxyhemoglobin level', 'Chest X-ray', 'Bronchoscopy'],
      medications: [
        { medication: 'Continue respiratory medications', instruction: 'continue', reason: 'Maintain respiratory function' }
      ],
      dietaryRestrictions: ['NPO for airway procedures'],
      physicalPreparation: ['Optimize oxygenation', 'Secretion clearance'],
      psychologicalPreparation: ['Explain need for intubation/ventilation if required'],
      consentRequirements: ['Intubation consent', 'Bronchoscopy consent', 'Tracheostomy consent if anticipated'],
      dayBeforeSurgery: ['Optimize respiratory status'],
      dayOfSurgery: ['NPO', 'Continue oxygen therapy']
    },
    
    intraoperativeInfo: {
      anesthesiaType: ['General anesthesia with careful airway management'],
      procedureDescription: 'Bronchoscopy for diagnosis and therapeutic lavage. Tracheostomy if prolonged airway support needed.',
      procedureSteps: [
        'Pre-oxygenation',
        'Careful intubation',
        'Bronchoscopic examination',
        'Lavage of airways',
        'Removal of debris',
        'Tracheostomy if indicated'
      ],
      duration: '30-90 minutes',
      techniques: ['Flexible bronchoscopy', 'Percutaneous or open tracheostomy'],
      expectedBloodLoss: 'Minimal',
      possibleComplications: ['Airway edema', 'Bronchospasm', 'Bleeding', 'Loss of airway']
    },
    
    postoperativeInstructions: {
      immediatePostop: {
        monitoring: ['Continuous SpO2 and ETCO2', 'Ventilator parameters', 'Chest X-ray'],
        positioning: 'Head of bed elevated 30-45 degrees',
        fluidManagement: 'Careful fluid balance - avoid overload',
        painControl: 'Sedation and analgesia as per ICU protocols',
        expectedSymptoms: ['Continued respiratory support need', 'Secretions'],
        nursingInstructions: ['Respiratory monitoring', 'Suctioning', 'Chest physiotherapy', 'Turn patient regularly']
      },
      woundCare: [
        { day: 'If tracheostomy', instruction: 'Tracheostomy care per protocol', frequency: 'Every 8 hours' }
      ],
      painManagement: {
        expectedPainLevel: 'Variable',
        medications: ['IV analgesia as needed'],
        nonPharmacological: ['Positioning', 'Suctioning for comfort'],
        whenToSeekHelp: 'Not applicable in ICU setting'
      },
      activityRestrictions: [
        { activity: 'All activity', restriction: 'Bed rest initially', duration: 'Until stable', reason: 'Respiratory support needs' }
      ],
      dietaryGuidelines: ['Enteral nutrition via NG tube if intubated', 'High calorie, high protein'],
      medicationRegimen: [
        { name: 'Bronchodilators', dose: 'As prescribed', frequency: 'Every 4-6 hours', purpose: 'Relieve bronchospasm' },
        { name: 'Mucolytics', dose: 'As prescribed', frequency: 'As needed', purpose: 'Clear secretions' }
      ],
      physicalTherapy: {
        startTiming: 'As soon as stable',
        frequency: 'Daily',
        exercises: [{ name: 'Chest physiotherapy', description: 'Positioning, percussion, breathing exercises', frequency: 'Multiple times daily' }],
        precautions: ['Monitor oxygen levels during therapy'],
        goals: ['Clear secretions', 'Maintain strength', 'Prevent complications']
      },
      returnToWork: 'Depends on severity; may be weeks to months',
      returnToNormalActivities: 'Gradual return as lung function permits'
    },
    
    expectedOutcomes: {
      shortTerm: [
        { timeframe: '1-2 weeks', expectation: 'Extubation and respiratory stability', indicators: ['Off ventilator', 'Stable oxygen levels'] }
      ],
      longTerm: [
        { timeframe: '3-12 months', expectation: 'Lung function recovery', indicators: ['Normal or near-normal PFTs', 'Normal activity tolerance'] }
      ],
      functionalRecovery: 'Most patients recover good lung function, though some may have persistent reactive airways disease',
      cosmeticOutcome: 'May have tracheostomy scar',
      qualityOfLife: 'Usually good if survive initial injury',
      possibleComplications: [
        { complication: 'ARDS', riskLevel: 'high', prevention: 'Lung-protective ventilation', management: 'ICU management' },
        { complication: 'Pneumonia', riskLevel: 'high', prevention: 'Early mobilization, pulmonary toilet', management: 'Antibiotics' },
        { complication: 'Reactive airways disease', riskLevel: 'moderate', prevention: 'None specific', management: 'Bronchodilators, steroids' }
      ],
      successRate: 'Survival 60-80% with modern ICU care; depends on severity and associated burns'
    },
    
    followUpCare: {
      schedule: [
        { timing: '2 weeks post-discharge', purpose: 'Respiratory assessment', whatToExpect: 'Clinical exam, pulse oximetry' },
        { timing: '3 months', purpose: 'Pulmonary function testing', whatToExpect: 'Spirometry, DLCO' },
        { timing: '1 year', purpose: 'Long-term assessment', whatToExpect: 'Full evaluation' }
      ],
      ongoingMonitoring: ['Lung function', 'Exercise tolerance', 'Symptoms'],
      rehabilitationNeeds: ['Pulmonary rehabilitation', 'Respiratory exercises'],
      supportServices: ['Pulmonology follow-up', 'Respiratory therapy'],
      longTermConsiderations: ['Monitor for chronic lung disease', 'Smoking cessation absolutely essential']
    },
    
    complianceRequirements: [
      { requirement: 'Use prescribed inhalers', importance: 'critical', consequence: 'Bronchospasm, poor lung function', tips: ['Use as directed', 'Learn proper technique'] },
      { requirement: 'Attend pulmonary rehab', importance: 'important', consequence: 'Slower recovery', tips: ['Complete full program'] },
      { requirement: 'Avoid smoking and smoke exposure', importance: 'critical', consequence: 'Permanent lung damage', tips: ['Never smoke again', 'Avoid secondhand smoke'] }
    ],
    
    whoGuidelines: [
      {
        title: 'WHO Burns and Inhalation Injury',
        reference: 'WHO Emergency Care Guidelines',
        keyPoints: [
          'High suspicion in enclosed space fires',
          'Early airway management is critical',
          'High-flow oxygen for CO poisoning',
          'Transfer to specialized center'
        ]
      }
    ],
    
    warningSigns: ['Increasing shortness of breath', 'New cough or wheeze', 'Fever', 'Increased sputum'],
    emergencySigns: ['Severe breathing difficulty', 'Blue lips or fingernails', 'Confusion', 'Unable to speak in sentences']
  }
];

export default burnsEducationPart3;
