#!/usr/bin/env node
/**
 * Combine every migration into one file to paste into the Supabase SQL editor.
 *
 *   npm run db:sql
 *
 * The no-credential path. `npm run db:migrate` is better — it records what it
 * applied in the migration history, so the next run knows what is already
 * there — but it needs the database password. This needs nothing except a
 * browser already logged into the Supabase dashboard.
 *
 * WHY ALL OF THEM, NOT JUST THE RECENT ONES
 * Working out which migrations are outstanding requires connecting to the
 * database, which is the thing this path exists to avoid. Every migration in
 * this repository is idempotent — that is checked before anything is written,
 * and the check fails the command if it is not — so running the whole set is
 * safe whatever state the database is in. Re-running an applied migration
 * changes nothing; missing an unapplied one is a broken feature.
 *
 * WHAT THIS DOES NOT DO
 * It does not write to `supabase_migrations.schema_migrations`. The CLI will
 * still think nothing has been applied, which is harmless precisely because
 * everything is re-runnable — but it means `npm run db:migrate` remains worth
 * running once when you have the password to hand.
 */

import { readdirSync, readFileSync, writeFileSync, mkdirSync } from 'node:fs';
import { join } from 'node:path';
import { checkMigrations, reportMigrations } from './check-migrations.mjs';

const DIR = 'supabase/migrations';
const OUT_DIR = 'supabase/.combined';
const OUT = join(OUT_DIR, 'all-migrations.sql');

const rule = (char = '=') => char.repeat(76);

function main() {
  // Refuse to build a paste-once file out of statements that cannot be re-run:
  // a failure halfway through the editor leaves the schema half-applied.
  const result = checkMigrations(DIR);
  if (!result.ok) {
    console.error('Not generating a combined file — some migrations are not safe to re-run:\n');
    reportMigrations(result);
    process.exit(1);
  }

  const files = readdirSync(DIR).filter(f => f.endsWith('.sql')).sort();
  if (!files.length) {
    console.error(`No migrations found in ${DIR}.`);
    process.exit(1);
  }

  const parts = [
    `-- ${rule()}`,
    '-- ALL MIGRATIONS, COMBINED',
    '--',
    `-- Generated by \`npm run db:sql\` on ${new Date().toISOString()}.`,
    `-- ${files.length} migration${files.length === 1 ? '' : 's'}, in the order they must run.`,
    '--',
    '-- Every statement is idempotent, so this is safe to run against a database',
    '-- in any state: already-applied migrations change nothing, and anything',
    '-- outstanding is applied. Safe to run more than once.',
    '--',
    '-- Paste the whole file into the Supabase SQL editor and run it.',
    `-- ${rule()}`,
    '',
    'BEGIN;',
    '',
  ];

  for (const file of files) {
    parts.push(
      '',
      `-- ${rule('-')}`,
      `-- ${file}`,
      `-- ${rule('-')}`,
      '',
      readFileSync(join(DIR, file), 'utf8').trimEnd(),
      '',
    );
  }

  // One transaction: either the whole schema moves forward or none of it does,
  // so a failure cannot leave the database in a state nobody has seen.
  parts.push('', 'COMMIT;', '');

  mkdirSync(OUT_DIR, { recursive: true });
  writeFileSync(OUT, parts.join('\n'), 'utf8');

  const lines = parts.join('\n').split('\n').length;
  console.log('Combined migration written.\n');
  console.log(`  File:       ${OUT}`);
  console.log(`  Migrations: ${files.length}`);
  console.log(`  Lines:      ${lines}\n`);
  for (const f of files) console.log(`    ${f}`);
  console.log('\nNext:');
  console.log('  1. Open the Supabase dashboard for this project → SQL Editor → New query.');
  console.log(`  2. Paste the whole contents of ${OUT}.`);
  console.log('  3. Run. It is wrapped in a transaction, so it either all applies or none does.');
  console.log('\nOr, with the database password to hand, `npm run db:migrate` does the same thing');
  console.log('and records it in the migration history so future runs know what is already there.');
}

main();
