#!/usr/bin/env node
/**
 * Generate a query that checks every migrated table actually exists.
 *
 *   npm run db:verify
 *
 * Applying a migration and believing it worked are different things. The SQL
 * editor reports "Success. No rows returned" for a script that created
 * everything and for one that created nothing — `CREATE TABLE IF NOT EXISTS`
 * succeeds either way — so the only way to know is to ask the database what it
 * has.
 *
 * The expected list is parsed out of the migration files rather than written
 * down here. A hand-maintained list is a list that goes stale the first time
 * someone adds a table and forgets, and a verification step that quietly stops
 * checking the newest thing is worse than none.
 */

import { readdirSync, readFileSync, writeFileSync, mkdirSync } from 'node:fs';
import { join } from 'node:path';

const DIR = 'supabase/migrations';
const OUT_DIR = 'supabase/.combined';
const OUT = join(OUT_DIR, 'verify.sql');

/** Every `CREATE TABLE IF NOT EXISTS [public.]name` across the migrations. */
function expectedTables() {
  const found = new Map(); // table -> migration that creates it
  const re = /CREATE\s+TABLE\s+IF\s+NOT\s+EXISTS\s+(?:public\.)?([A-Za-z0-9_]+)/gi;

  for (const file of readdirSync(DIR).filter(f => f.endsWith('.sql')).sort()) {
    const sql = readFileSync(join(DIR, file), 'utf8');
    let m;
    while ((m = re.exec(sql)) !== null) {
      if (!found.has(m[1])) found.set(m[1], file);
    }
  }
  return found;
}

function main() {
  const tables = expectedTables();
  if (!tables.size) {
    console.error('No CREATE TABLE statements found — nothing to verify.');
    process.exit(1);
  }

  const names = [...tables.keys()].sort();

  // A VALUES list left-joined against the catalogue: every expected table gets
  // a row whether or not it exists, so a missing one shows up as a row saying
  // MISSING rather than as an absent row nobody notices.
  const sql = `-- Verify every table the migrations should have created.
-- Generated by \`npm run db:verify\` on ${new Date().toISOString()}.
-- Paste into the Supabase SQL editor and run. Every row should read 'ok'.

SELECT
  e.table_name,
  CASE WHEN t.tablename IS NULL THEN 'MISSING' ELSE 'ok' END AS status
FROM (VALUES
${names.map(n => `  ('${n}')`).join(',\n')}
) AS e(table_name)
LEFT JOIN pg_tables t
  ON t.schemaname = 'public' AND t.tablename = e.table_name
ORDER BY status DESC, e.table_name;
`;

  mkdirSync(OUT_DIR, { recursive: true });
  writeFileSync(OUT, sql, 'utf8');

  console.log(`Verification query written to ${OUT}`);
  console.log(`Checking ${names.length} tables across ${new Set(tables.values()).size} migrations.\n`);
  console.log('Paste it into the Supabase SQL editor. Every row should read "ok";');
  console.log('anything reading "MISSING" sorts to the top.');
}

main();
