-- ============================================================================
-- Frontend <-> Backend schema reconciliation
-- ----------------------------------------------------------------------------
-- Generated by auditing every TypeScript model that the cloud sync engine
-- pushes (src/database/db.ts -> src/services/cloudSyncService.ts) against the
-- columns actually declared across every SQL migration in this repo.
--
-- Each field below is written by the client but had no column to land in. The
-- PGRST204 handler in cloudSyncService.ts (markColumnExcluded) was silently
-- stripping them from every upsert, so the values never persisted.
--
-- All statements are additive and idempotent - safe to re-run.
--
-- Each block is guarded on the table existing. The base tables come from the
-- supabase-*.sql files at the repo root, which are applied by hand, so a given
-- deployment may legitimately not have all of them yet. Without the guard one
-- absent table would abort the whole migration and block every other change.
-- ============================================================================

-- ---------------------------------------------------------------------------
-- 1. Sync watermark columns
-- pullTable() orders by updated_at and pushTable() uses it as the dirty-record
-- watermark. These tables had no such column, so they could not sync at all.
-- ---------------------------------------------------------------------------

-- finance_income  (sync watermark)
DO $$
BEGIN
  IF to_regclass('public.finance_income') IS NOT NULL THEN
    ALTER TABLE public.finance_income ADD COLUMN IF NOT EXISTS updated_at TIMESTAMPTZ DEFAULT NOW();
  ELSE
    RAISE NOTICE 'skipped %: table not present', 'finance_income';
  END IF;
END $$;

-- finance_transactions  (sync watermark)
DO $$
BEGIN
  IF to_regclass('public.finance_transactions') IS NOT NULL THEN
    ALTER TABLE public.finance_transactions ADD COLUMN IF NOT EXISTS updated_at TIMESTAMPTZ DEFAULT NOW();
  ELSE
    RAISE NOTICE 'skipped %: table not present', 'finance_transactions';
  END IF;
END $$;

-- finance_expenses  (sync watermark)
DO $$
BEGIN
  IF to_regclass('public.finance_expenses') IS NOT NULL THEN
    ALTER TABLE public.finance_expenses ADD COLUMN IF NOT EXISTS updated_at TIMESTAMPTZ DEFAULT NOW();
  ELSE
    RAISE NOTICE 'skipped %: table not present', 'finance_expenses';
  END IF;
END $$;

-- finance_investments  (sync watermark)
DO $$
BEGIN
  IF to_regclass('public.finance_investments') IS NOT NULL THEN
    ALTER TABLE public.finance_investments ADD COLUMN IF NOT EXISTS updated_at TIMESTAMPTZ DEFAULT NOW();
  ELSE
    RAISE NOTICE 'skipped %: table not present', 'finance_investments';
  END IF;
END $$;

-- finance_audit_logs  (sync watermark)
DO $$
BEGIN
  IF to_regclass('public.finance_audit_logs') IS NOT NULL THEN
    ALTER TABLE public.finance_audit_logs ADD COLUMN IF NOT EXISTS updated_at TIMESTAMPTZ DEFAULT NOW();
    ALTER TABLE public.finance_audit_logs ADD COLUMN IF NOT EXISTS created_at TIMESTAMPTZ DEFAULT NOW();
  ELSE
    RAISE NOTICE 'skipped %: table not present', 'finance_audit_logs';
  END IF;
END $$;

-- ---------------------------------------------------------------------------
-- 2. Missing model columns (364 across 45 tables)
-- ---------------------------------------------------------------------------

-- activity_billing_records  (10 columns)
DO $$
BEGIN
  IF to_regclass('public.activity_billing_records') IS NOT NULL THEN
    ALTER TABLE public.activity_billing_records ADD COLUMN IF NOT EXISTS activity_id TEXT; -- activityId: string
    ALTER TABLE public.activity_billing_records ADD COLUMN IF NOT EXISTS encounter_id TEXT; -- encounterId: string
    ALTER TABLE public.activity_billing_records ADD COLUMN IF NOT EXISTS fee NUMERIC; -- fee: number
    ALTER TABLE public.activity_billing_records ADD COLUMN IF NOT EXISTS original_fee NUMERIC; -- originalFee: number
    ALTER TABLE public.activity_billing_records ADD COLUMN IF NOT EXISTS discount_amount NUMERIC; -- discountAmount: number
    ALTER TABLE public.activity_billing_records ADD COLUMN IF NOT EXISTS discount_rate NUMERIC; -- discountRate: number
    ALTER TABLE public.activity_billing_records ADD COLUMN IF NOT EXISTS npwt_session_id TEXT; -- npwtSessionId: string
    ALTER TABLE public.activity_billing_records ADD COLUMN IF NOT EXISTS transfusion_id TEXT; -- transfusionId: string
    ALTER TABLE public.activity_billing_records ADD COLUMN IF NOT EXISTS payment_method TEXT; -- paymentMethod: 'cash' | 'card' | 'transfer' | 'insurance'
    ALTER TABLE public.activity_billing_records ADD COLUMN IF NOT EXISTS payment_evidence_url TEXT; -- paymentEvidenceUrl: string
  ELSE
    RAISE NOTICE 'skipped %: table not present', 'activity_billing_records';
  END IF;
END $$;

-- appointment_reminders  (5 columns)
DO $$
BEGIN
  IF to_regclass('public.appointment_reminders') IS NOT NULL THEN
    ALTER TABLE public.appointment_reminders ADD COLUMN IF NOT EXISTS message_template TEXT; -- messageTemplate: string
    ALTER TABLE public.appointment_reminders ADD COLUMN IF NOT EXISTS whatsapp_number TEXT; -- whatsAppNumber: string
    ALTER TABLE public.appointment_reminders ADD COLUMN IF NOT EXISTS patient_response TEXT; -- patientResponse: 'confirmed' | 'cancelled' | 'rescheduled' | 'n
    ALTER TABLE public.appointment_reminders ADD COLUMN IF NOT EXISTS response_received_at TIMESTAMPTZ; -- responseReceivedAt: Date
    ALTER TABLE public.appointment_reminders ADD COLUMN IF NOT EXISTS failure_reason TEXT; -- failureReason: string
  ELSE
    RAISE NOTICE 'skipped %: table not present', 'appointment_reminders';
  END IF;
END $$;

-- appointment_slots  (1 column)
DO $$
BEGIN
  IF to_regclass('public.appointment_slots') IS NOT NULL THEN
    ALTER TABLE public.appointment_slots ADD COLUMN IF NOT EXISTS location_type TEXT; -- locationType: 'hospital' | 'home' | 'telemedicine'
  ELSE
    RAISE NOTICE 'skipped %: table not present', 'appointment_slots';
  END IF;
END $$;

-- appointments  (3 columns)
DO $$
BEGIN
  IF to_regclass('public.appointments') IS NOT NULL THEN
    ALTER TABLE public.appointments ADD COLUMN IF NOT EXISTS patient_whatsapp TEXT; -- patientWhatsApp: string
    ALTER TABLE public.appointments ADD COLUMN IF NOT EXISTS reminder_enabled BOOLEAN; -- reminderEnabled: boolean
    ALTER TABLE public.appointments ADD COLUMN IF NOT EXISTS sync_status TEXT;     -- syncStatus: 'pending' | 'synced' | 'conflict'
  ELSE
    RAISE NOTICE 'skipped %: table not present', 'appointments';
  END IF;
END $$;

-- burn_care_plans  (4 columns)
DO $$
BEGIN
  IF to_regclass('public.burn_care_plans') IS NOT NULL THEN
    ALTER TABLE public.burn_care_plans ADD COLUMN IF NOT EXISTS current_phase TEXT; -- currentPhase: 'resuscitation' | 'acute' | 'grafting' | 'reha
    ALTER TABLE public.burn_care_plans ADD COLUMN IF NOT EXISTS resuscitation_goals JSONB; -- resuscitationGoals: ResuscitationGoals
    ALTER TABLE public.burn_care_plans ADD COLUMN IF NOT EXISTS fluid_orders JSONB; -- fluidOrders: FluidOrder[]
    ALTER TABLE public.burn_care_plans ADD COLUMN IF NOT EXISTS primary_surgeon TEXT; -- primarySurgeon: string
  ELSE
    RAISE NOTICE 'skipped %: table not present', 'burn_care_plans';
  END IF;
END $$;

-- burn_monitoring_records  (6 columns)
DO $$
BEGIN
  IF to_regclass('public.burn_monitoring_records') IS NOT NULL THEN
    ALTER TABLE public.burn_monitoring_records ADD COLUMN IF NOT EXISTS vitals JSONB; -- vitals: BurnMonitoringVitals
    ALTER TABLE public.burn_monitoring_records ADD COLUMN IF NOT EXISTS urine_output JSONB; -- urineOutput: BurnUrineOutput
    ALTER TABLE public.burn_monitoring_records ADD COLUMN IF NOT EXISTS fluid_administered JSONB; -- fluidAdministered: BurnFluidAdministered
    ALTER TABLE public.burn_monitoring_records ADD COLUMN IF NOT EXISTS gcs_score JSONB; -- gcsScore: GCSScore
    ALTER TABLE public.burn_monitoring_records ADD COLUMN IF NOT EXISTS labs JSONB; -- labs: BurnMonitoringLabs
    ALTER TABLE public.burn_monitoring_records ADD COLUMN IF NOT EXISTS alerts JSONB; -- alerts: BurnMonitoringAlert[]
  ELSE
    RAISE NOTICE 'skipped %: table not present', 'burn_monitoring_records';
  END IF;
END $$;

-- clinic_sessions  (4 columns)
DO $$
BEGIN
  IF to_regclass('public.clinic_sessions') IS NOT NULL THEN
    ALTER TABLE public.clinic_sessions ADD COLUMN IF NOT EXISTS clinician_ids JSONB; -- clinicianIds: string[]
    ALTER TABLE public.clinic_sessions ADD COLUMN IF NOT EXISTS assigned_nurse_id TEXT; -- assignedNurseId: string
    ALTER TABLE public.clinic_sessions ADD COLUMN IF NOT EXISTS notifications_sent BOOLEAN; -- notificationsSent: boolean
    ALTER TABLE public.clinic_sessions ADD COLUMN IF NOT EXISTS notification_sent_at TIMESTAMPTZ; -- notificationSentAt: Date
  ELSE
    RAISE NOTICE 'skipped %: table not present', 'clinic_sessions';
  END IF;
END $$;

-- clinical_comments  (7 columns)
DO $$
BEGIN
  IF to_regclass('public.clinical_comments') IS NOT NULL THEN
    ALTER TABLE public.clinical_comments ADD COLUMN IF NOT EXISTS entity_type TEXT; -- entityType: CommentableEntityType
    ALTER TABLE public.clinical_comments ADD COLUMN IF NOT EXISTS comment TEXT;    -- comment: string
    ALTER TABLE public.clinical_comments ADD COLUMN IF NOT EXISTS is_resolved BOOLEAN; -- isResolved: boolean
    ALTER TABLE public.clinical_comments ADD COLUMN IF NOT EXISTS parent_comment_id TEXT; -- parentCommentId: string
    ALTER TABLE public.clinical_comments ADD COLUMN IF NOT EXISTS author_id TEXT;  -- authorId: string
    ALTER TABLE public.clinical_comments ADD COLUMN IF NOT EXISTS created_at TIMESTAMPTZ; -- createdAt: Date
    ALTER TABLE public.clinical_comments ADD COLUMN IF NOT EXISTS synced_at TIMESTAMPTZ; -- syncedAt: Date
  ELSE
    RAISE NOTICE 'skipped %: table not present', 'clinical_comments';
  END IF;
END $$;

-- clinical_encounters  (1 column)
DO $$
BEGIN
  IF to_regclass('public.clinical_encounters') IS NOT NULL THEN
    ALTER TABLE public.clinical_encounters ADD COLUMN IF NOT EXISTS lmp TEXT;      -- lmp: string
  ELSE
    RAISE NOTICE 'skipped %: table not present', 'clinical_encounters';
  END IF;
END $$;

-- clinician_analyses  (1 column)
DO $$
BEGIN
  IF to_regclass('public.clinician_analyses') IS NOT NULL THEN
    ALTER TABLE public.clinician_analyses ADD COLUMN IF NOT EXISTS first_name TEXT; -- firstName: string
  ELSE
    RAISE NOTICE 'skipped %: table not present', 'clinician_analyses';
  END IF;
END $$;

-- detox_follow_ups  (11 columns)
DO $$
BEGIN
  IF to_regclass('public.detox_follow_ups') IS NOT NULL THEN
    ALTER TABLE public.detox_follow_ups ADD COLUMN IF NOT EXISTS status TEXT;      -- status: 'scheduled' | 'completed' | 'missed' | 'resche
    ALTER TABLE public.detox_follow_ups ADD COLUMN IF NOT EXISTS follow_up_type TEXT; -- followUpType: 'phone' | 'in_person' | 'video' | 'home_visit'
    ALTER TABLE public.detox_follow_ups ADD COLUMN IF NOT EXISTS current_status TEXT; -- currentStatus: 'abstinent' | 'reduced_use' | 'same_level' | '
    ALTER TABLE public.detox_follow_ups ADD COLUMN IF NOT EXISTS relapse_risk_level TEXT; -- relapseRiskLevel: 'low' | 'moderate' | 'high'
    ALTER TABLE public.detox_follow_ups ADD COLUMN IF NOT EXISTS adherence_to_recommendations TEXT; -- adherenceToRecommendations: 'full' | 'partial' | 'none'
    ALTER TABLE public.detox_follow_ups ADD COLUMN IF NOT EXISTS withdrawal_symptoms_resolved BOOLEAN; -- withdrawalSymptomsResolved: boolean
    ALTER TABLE public.detox_follow_ups ADD COLUMN IF NOT EXISTS support_system_strength TEXT; -- supportSystemStrength: 'strong' | 'moderate' | 'weak' | 'none'
    ALTER TABLE public.detox_follow_ups ADD COLUMN IF NOT EXISTS referrals_provided JSONB; -- referralsProvided: string[]
    ALTER TABLE public.detox_follow_ups ADD COLUMN IF NOT EXISTS counseling_recommended BOOLEAN; -- counselingRecommended: boolean
    ALTER TABLE public.detox_follow_ups ADD COLUMN IF NOT EXISTS next_steps JSONB; -- nextSteps: string[]
    ALTER TABLE public.detox_follow_ups ADD COLUMN IF NOT EXISTS created_at TIMESTAMPTZ; -- createdAt: Date
  ELSE
    RAISE NOTICE 'skipped %: table not present', 'detox_follow_ups';
  END IF;
END $$;

-- detox_monitoring_records  (25 columns)
DO $$
BEGIN
  IF to_regclass('public.detox_monitoring_records') IS NOT NULL THEN
    ALTER TABLE public.detox_monitoring_records ADD COLUMN IF NOT EXISTS recorded_by TEXT; -- recordedBy: string
    ALTER TABLE public.detox_monitoring_records ADD COLUMN IF NOT EXISTS temperature NUMERIC; -- temperature: number
    ALTER TABLE public.detox_monitoring_records ADD COLUMN IF NOT EXISTS pulse NUMERIC; -- pulse: number
    ALTER TABLE public.detox_monitoring_records ADD COLUMN IF NOT EXISTS blood_pressure TEXT; -- bloodPressure: string
    ALTER TABLE public.detox_monitoring_records ADD COLUMN IF NOT EXISTS respiratory_rate NUMERIC; -- respiratoryRate: number
    ALTER TABLE public.detox_monitoring_records ADD COLUMN IF NOT EXISTS oxygen_saturation NUMERIC; -- oxygenSaturation: number
    ALTER TABLE public.detox_monitoring_records ADD COLUMN IF NOT EXISTS withdrawal_symptoms JSONB; -- withdrawalSymptoms: string[]
    ALTER TABLE public.detox_monitoring_records ADD COLUMN IF NOT EXISTS ciwa_score NUMERIC; -- ciwaScore: number
    ALTER TABLE public.detox_monitoring_records ADD COLUMN IF NOT EXISTS cows_score NUMERIC; -- cowsScore: number
    ALTER TABLE public.detox_monitoring_records ADD COLUMN IF NOT EXISTS paws_present BOOLEAN; -- pawsPresent: boolean
    ALTER TABLE public.detox_monitoring_records ADD COLUMN IF NOT EXISTS pain_score NUMERIC; -- painScore: number
    ALTER TABLE public.detox_monitoring_records ADD COLUMN IF NOT EXISTS pain_location TEXT; -- painLocation: string
    ALTER TABLE public.detox_monitoring_records ADD COLUMN IF NOT EXISTS anxiety_level TEXT; -- anxietyLevel: 'none' | 'mild' | 'moderate' | 'severe'
    ALTER TABLE public.detox_monitoring_records ADD COLUMN IF NOT EXISTS agitation_level TEXT; -- agitationLevel: 'none' | 'mild' | 'moderate' | 'severe'
    ALTER TABLE public.detox_monitoring_records ADD COLUMN IF NOT EXISTS sleep_quality TEXT; -- sleepQuality: 'good' | 'fair' | 'poor' | 'none'
    ALTER TABLE public.detox_monitoring_records ADD COLUMN IF NOT EXISTS hallucinations_present BOOLEAN; -- hallucinationsPresent: boolean
    ALTER TABLE public.detox_monitoring_records ADD COLUMN IF NOT EXISTS suicidal_ideation BOOLEAN; -- suicidalIdeation: boolean
    ALTER TABLE public.detox_monitoring_records ADD COLUMN IF NOT EXISTS medication_compliance BOOLEAN; -- medicationCompliance: boolean
    ALTER TABLE public.detox_monitoring_records ADD COLUMN IF NOT EXISTS fluid_intake_adequate BOOLEAN; -- fluidIntakeAdequate: boolean
    ALTER TABLE public.detox_monitoring_records ADD COLUMN IF NOT EXISTS nutrition_intake_adequate BOOLEAN; -- nutritionIntakeAdequate: boolean
    ALTER TABLE public.detox_monitoring_records ADD COLUMN IF NOT EXISTS medications_given JSONB; -- medicationsGiven: Array<{
    ALTER TABLE public.detox_monitoring_records ADD COLUMN IF NOT EXISTS notes TEXT; -- notes: string
    ALTER TABLE public.detox_monitoring_records ADD COLUMN IF NOT EXISTS alerts_triggered JSONB; -- alertsTriggered: string[]
    ALTER TABLE public.detox_monitoring_records ADD COLUMN IF NOT EXISTS requires_escalation BOOLEAN; -- requiresEscalation: boolean
    ALTER TABLE public.detox_monitoring_records ADD COLUMN IF NOT EXISTS escalation_reason TEXT; -- escalationReason: string
  ELSE
    RAISE NOTICE 'skipped %: table not present', 'detox_monitoring_records';
  END IF;
END $$;

-- escharotomy_records  (12 columns)
DO $$
BEGIN
  IF to_regclass('public.escharotomy_records') IS NOT NULL THEN
    ALTER TABLE public.escharotomy_records ADD COLUMN IF NOT EXISTS location TEXT; -- location: string
    ALTER TABLE public.escharotomy_records ADD COLUMN IF NOT EXISTS pre_operative_findings JSONB; -- preOperativeFindings: {
    ALTER TABLE public.escharotomy_records ADD COLUMN IF NOT EXISTS procedure_date_time TIMESTAMPTZ; -- procedureDateTime: Date
    ALTER TABLE public.escharotomy_records ADD COLUMN IF NOT EXISTS date TIMESTAMPTZ; -- date: Date
    ALTER TABLE public.escharotomy_records ADD COLUMN IF NOT EXISTS surgeon TEXT;  -- surgeon: string
    ALTER TABLE public.escharotomy_records ADD COLUMN IF NOT EXISTS performer TEXT; -- performer: string
    ALTER TABLE public.escharotomy_records ADD COLUMN IF NOT EXISTS assistants JSONB; -- assistants: string[]
    ALTER TABLE public.escharotomy_records ADD COLUMN IF NOT EXISTS technique TEXT; -- technique: string
    ALTER TABLE public.escharotomy_records ADD COLUMN IF NOT EXISTS incision_length NUMERIC; -- incisionLength: number
    ALTER TABLE public.escharotomy_records ADD COLUMN IF NOT EXISTS post_operative_findings JSONB; -- postOperativeFindings: {
    ALTER TABLE public.escharotomy_records ADD COLUMN IF NOT EXISTS indications JSONB; -- indications: string[]
    ALTER TABLE public.escharotomy_records ADD COLUMN IF NOT EXISTS immediate_result TEXT; -- immediateResult: 'restored_perfusion' | 'improved_perfusion' | 
  ELSE
    RAISE NOTICE 'skipped %: table not present', 'escharotomy_records';
  END IF;
END $$;

-- hospital_settings  (7 columns)
DO $$
BEGIN
  IF to_regclass('public.hospital_settings') IS NOT NULL THEN
    ALTER TABLE public.hospital_settings ADD COLUMN IF NOT EXISTS logo_url TEXT;   -- logoUrl: string
    ALTER TABLE public.hospital_settings ADD COLUMN IF NOT EXISTS default_consultation_fee NUMERIC; -- defaultConsultationFee: number
    ALTER TABLE public.hospital_settings ADD COLUMN IF NOT EXISTS wards JSONB;     -- wards: { name: string
    ALTER TABLE public.hospital_settings ADD COLUMN IF NOT EXISTS appointment_slot_duration NUMERIC; -- appointmentSlotDuration: number
    ALTER TABLE public.hospital_settings ADD COLUMN IF NOT EXISTS default_d_v_t_prophylaxis TEXT; -- defaultDVTProphylaxis: string
    ALTER TABLE public.hospital_settings ADD COLUMN IF NOT EXISTS sync_interval_minutes NUMERIC; -- syncIntervalMinutes: number
    ALTER TABLE public.hospital_settings ADD COLUMN IF NOT EXISTS offline_storage_limit_m_b NUMERIC; -- offlineStorageLimitMB: number
  ELSE
    RAISE NOTICE 'skipped %: table not present', 'hospital_settings';
  END IF;
END $$;

-- investigation_approval_logs  (3 columns)
DO $$
BEGIN
  IF to_regclass('public.investigation_approval_logs') IS NOT NULL THEN
    ALTER TABLE public.investigation_approval_logs ADD COLUMN IF NOT EXISTS action TEXT; -- action: ApprovalAction
    ALTER TABLE public.investigation_approval_logs ADD COLUMN IF NOT EXISTS source_investigation_id TEXT; -- sourceInvestigationId: string
    ALTER TABLE public.investigation_approval_logs ADD COLUMN IF NOT EXISTS synced_at TIMESTAMPTZ; -- syncedAt: Date
  ELSE
    RAISE NOTICE 'skipped %: table not present', 'investigation_approval_logs';
  END IF;
END $$;

-- investigations  (5 columns)
DO $$
BEGIN
  IF to_regclass('public.investigations') IS NOT NULL THEN
    ALTER TABLE public.investigations ADD COLUMN IF NOT EXISTS rejected_by TEXT;   -- rejectedBy: string
    ALTER TABLE public.investigations ADD COLUMN IF NOT EXISTS rejected_by_name TEXT; -- rejectedByName: string
    ALTER TABLE public.investigations ADD COLUMN IF NOT EXISTS rejected_at TIMESTAMPTZ; -- rejectedAt: Date
    ALTER TABLE public.investigations ADD COLUMN IF NOT EXISTS auto_requested BOOLEAN; -- autoRequested: boolean
    ALTER TABLE public.investigations ADD COLUMN IF NOT EXISTS source_approval_id TEXT; -- sourceApprovalId: string
  ELSE
    RAISE NOTICE 'skipped %: table not present', 'investigations';
  END IF;
END $$;

-- lab_requests  (3 columns)
DO $$
BEGIN
  IF to_regclass('public.lab_requests') IS NOT NULL THEN
    ALTER TABLE public.lab_requests ADD COLUMN IF NOT EXISTS patient_name TEXT;    -- patientName: string
    ALTER TABLE public.lab_requests ADD COLUMN IF NOT EXISTS hospital_number TEXT; -- hospitalNumber: string
    ALTER TABLE public.lab_requests ADD COLUMN IF NOT EXISTS source TEXT;          -- source: string
  ELSE
    RAISE NOTICE 'skipped %: table not present', 'lab_requests';
  END IF;
END $$;

-- lymphedema_assessments  (25 columns)
DO $$
BEGIN
  IF to_regclass('public.lymphedema_assessments') IS NOT NULL THEN
    ALTER TABLE public.lymphedema_assessments ADD COLUMN IF NOT EXISTS assessed_by_name TEXT; -- assessedByName: string
    ALTER TABLE public.lymphedema_assessments ADD COLUMN IF NOT EXISTS status TEXT; -- status: AssessmentStatus
    ALTER TABLE public.lymphedema_assessments ADD COLUMN IF NOT EXISTS etiology_details TEXT; -- etiologyDetails: string
    ALTER TABLE public.lymphedema_assessments ADD COLUMN IF NOT EXISTS affected_limb TEXT; -- affectedLimb: LymphedemaLimb
    ALTER TABLE public.lymphedema_assessments ADD COLUMN IF NOT EXISTS is_unilateral BOOLEAN; -- isUnilateral: boolean
    ALTER TABLE public.lymphedema_assessments ADD COLUMN IF NOT EXISTS previous_surgery JSONB; -- previousSurgery: string[]
    ALTER TABLE public.lymphedema_assessments ADD COLUMN IF NOT EXISTS radiation_history BOOLEAN; -- radiationHistory: boolean
    ALTER TABLE public.lymphedema_assessments ADD COLUMN IF NOT EXISTS radiation_details TEXT; -- radiationDetails: string
    ALTER TABLE public.lymphedema_assessments ADD COLUMN IF NOT EXISTS filariasis_status TEXT; -- filariasisStatus: 'positive' | 'negative' | 'not_tested'
    ALTER TABLE public.lymphedema_assessments ADD COLUMN IF NOT EXISTS episodes_of_cellulitis NUMERIC; -- episodesOfCellulitis: number
    ALTER TABLE public.lymphedema_assessments ADD COLUMN IF NOT EXISTS last_cellulitis_date TEXT; -- lastCellulitisDate: string
    ALTER TABLE public.lymphedema_assessments ADD COLUMN IF NOT EXISTS medications JSONB; -- medications: string[]
    ALTER TABLE public.lymphedema_assessments ADD COLUMN IF NOT EXISTS bmi NUMERIC; -- bmi: number
    ALTER TABLE public.lymphedema_assessments ADD COLUMN IF NOT EXISTS kaposi_stemmer_positive BOOLEAN; -- kaposi_stemmer_positive: boolean
    ALTER TABLE public.lymphedema_assessments ADD COLUMN IF NOT EXISTS limb_measurements JSONB; -- limbMeasurements: LimbMeasurement[]
    ALTER TABLE public.lymphedema_assessments ADD COLUMN IF NOT EXISTS volume_calculation JSONB; -- volumeCalculation: LimbVolumeCalculation
    ALTER TABLE public.lymphedema_assessments ADD COLUMN IF NOT EXISTS bioimpedance JSONB; -- bioimpedance: BioimpedanceResult
    ALTER TABLE public.lymphedema_assessments ADD COLUMN IF NOT EXISTS isl_stage TEXT; -- islStage: ISLStage
    ALTER TABLE public.lymphedema_assessments ADD COLUMN IF NOT EXISTS severity_score JSONB; -- severityScore: LymphedemaSeverityScore
    ALTER TABLE public.lymphedema_assessments ADD COLUMN IF NOT EXISTS investigations_ordered JSONB; -- investigationsOrdered: LymphedemaInvestigation[]
    ALTER TABLE public.lymphedema_assessments ADD COLUMN IF NOT EXISTS current_treatment_phase TEXT; -- currentTreatmentPhase: TreatmentPhase
    ALTER TABLE public.lymphedema_assessments ADD COLUMN IF NOT EXISTS treatment_plan JSONB; -- treatmentPlan: LymphedemaTreatmentPlan
    ALTER TABLE public.lymphedema_assessments ADD COLUMN IF NOT EXISTS surgical_candidacy JSONB; -- surgicalCandidacy: SurgicalCandidacyAssessment
    ALTER TABLE public.lymphedema_assessments ADD COLUMN IF NOT EXISTS audit_log JSONB; -- auditLog: LymphedemaAuditEntry[]
    ALTER TABLE public.lymphedema_assessments ADD COLUMN IF NOT EXISTS created_at TIMESTAMPTZ; -- createdAt: Date
  ELSE
    RAISE NOTICE 'skipped %: table not present', 'lymphedema_assessments';
  END IF;
END $$;

-- lymphedema_monitoring_records  (32 columns)
DO $$
BEGIN
  IF to_regclass('public.lymphedema_monitoring_records') IS NOT NULL THEN
    ALTER TABLE public.lymphedema_monitoring_records ADD COLUMN IF NOT EXISTS hospital_id TEXT; -- hospitalId: string
    ALTER TABLE public.lymphedema_monitoring_records ADD COLUMN IF NOT EXISTS record_date TIMESTAMPTZ; -- recordDate: Date
    ALTER TABLE public.lymphedema_monitoring_records ADD COLUMN IF NOT EXISTS recorded_by TEXT; -- recordedBy: string
    ALTER TABLE public.lymphedema_monitoring_records ADD COLUMN IF NOT EXISTS recorded_by_name TEXT; -- recordedByName: string
    ALTER TABLE public.lymphedema_monitoring_records ADD COLUMN IF NOT EXISTS treatment_phase TEXT; -- treatmentPhase: TreatmentPhase
    ALTER TABLE public.lymphedema_monitoring_records ADD COLUMN IF NOT EXISTS session_number NUMERIC; -- sessionNumber: number
    ALTER TABLE public.lymphedema_monitoring_records ADD COLUMN IF NOT EXISTS limb_measurements JSONB; -- limbMeasurements: LimbMeasurement[]
    ALTER TABLE public.lymphedema_monitoring_records ADD COLUMN IF NOT EXISTS volume_calculation JSONB; -- volumeCalculation: LimbVolumeCalculation
    ALTER TABLE public.lymphedema_monitoring_records ADD COLUMN IF NOT EXISTS calculated_volume_ml NUMERIC; -- calculatedVolumeMl: number
    ALTER TABLE public.lymphedema_monitoring_records ADD COLUMN IF NOT EXISTS volume_change_from_baseline NUMERIC; -- volumeChangeFromBaseline: number
    ALTER TABLE public.lymphedema_monitoring_records ADD COLUMN IF NOT EXISTS volume_change_from_last NUMERIC; -- volumeChangeFromLast: number
    ALTER TABLE public.lymphedema_monitoring_records ADD COLUMN IF NOT EXISTS pitting_grade TEXT; -- pittingGrade: PittingGrade
    ALTER TABLE public.lymphedema_monitoring_records ADD COLUMN IF NOT EXISTS pain_score NUMERIC; -- painScore: number
    ALTER TABLE public.lymphedema_monitoring_records ADD COLUMN IF NOT EXISTS heaviness_score NUMERIC; -- heavinessScore: number
    ALTER TABLE public.lymphedema_monitoring_records ADD COLUMN IF NOT EXISTS tightness_score NUMERIC; -- tightnessScore: number
    ALTER TABLE public.lymphedema_monitoring_records ADD COLUMN IF NOT EXISTS compression_compliance TEXT; -- compressionCompliance: 'excellent' | 'good' | 'fair' | 'poor' | 'non_
    ALTER TABLE public.lymphedema_monitoring_records ADD COLUMN IF NOT EXISTS compression_issues TEXT; -- compressionIssues: string
    ALTER TABLE public.lymphedema_monitoring_records ADD COLUMN IF NOT EXISTS mld_performed BOOLEAN; -- mldPerformed: boolean
    ALTER TABLE public.lymphedema_monitoring_records ADD COLUMN IF NOT EXISTS mld_response TEXT; -- mldResponse: 'good' | 'moderate' | 'poor' | 'not_applicable
    ALTER TABLE public.lymphedema_monitoring_records ADD COLUMN IF NOT EXISTS bandaging_applied BOOLEAN; -- bandagingApplied: boolean
    ALTER TABLE public.lymphedema_monitoring_records ADD COLUMN IF NOT EXISTS bandaging_type TEXT; -- bandagingType: BandagingType
    ALTER TABLE public.lymphedema_monitoring_records ADD COLUMN IF NOT EXISTS exercises_performed BOOLEAN; -- exercisesPerformed: boolean
    ALTER TABLE public.lymphedema_monitoring_records ADD COLUMN IF NOT EXISTS skin_care_performed BOOLEAN; -- skinCarePerformed: boolean
    ALTER TABLE public.lymphedema_monitoring_records ADD COLUMN IF NOT EXISTS signs_of_infection BOOLEAN; -- signsOfInfection: boolean
    ALTER TABLE public.lymphedema_monitoring_records ADD COLUMN IF NOT EXISTS infection_details TEXT; -- infectionDetails: string
    ALTER TABLE public.lymphedema_monitoring_records ADD COLUMN IF NOT EXISTS range_of_motion_degrees JSONB; -- rangeOfMotionDegrees: Record<string, number>
    ALTER TABLE public.lymphedema_monitoring_records ADD COLUMN IF NOT EXISTS functional_status TEXT; -- functionalStatus: string
    ALTER TABLE public.lymphedema_monitoring_records ADD COLUMN IF NOT EXISTS photo_urls JSONB; -- photoUrls: string[]
    ALTER TABLE public.lymphedema_monitoring_records ADD COLUMN IF NOT EXISTS clinician_notes TEXT; -- clinicianNotes: string
    ALTER TABLE public.lymphedema_monitoring_records ADD COLUMN IF NOT EXISTS plan_adjustments TEXT; -- planAdjustments: string
    ALTER TABLE public.lymphedema_monitoring_records ADD COLUMN IF NOT EXISTS alerts JSONB; -- alerts: LymphedemaAlert[]
    ALTER TABLE public.lymphedema_monitoring_records ADD COLUMN IF NOT EXISTS created_at TIMESTAMPTZ; -- createdAt: Date
  ELSE
    RAISE NOTICE 'skipped %: table not present', 'lymphedema_monitoring_records';
  END IF;
END $$;

-- mdt_meetings  (8 columns)
DO $$
BEGIN
  IF to_regclass('public.mdt_meetings') IS NOT NULL THEN
    ALTER TABLE public.mdt_meetings ADD COLUMN IF NOT EXISTS title TEXT;           -- title: string
    ALTER TABLE public.mdt_meetings ADD COLUMN IF NOT EXISTS scheduled_date TIMESTAMPTZ; -- scheduledDate: Date
    ALTER TABLE public.mdt_meetings ADD COLUMN IF NOT EXISTS duration NUMERIC;     -- duration: number
    ALTER TABLE public.mdt_meetings ADD COLUMN IF NOT EXISTS virtual_link TEXT;    -- virtualLink: string
    ALTER TABLE public.mdt_meetings ADD COLUMN IF NOT EXISTS agenda JSONB;         -- agenda: AgendaItem[]
    ALTER TABLE public.mdt_meetings ADD COLUMN IF NOT EXISTS decisions JSONB;      -- decisions: MDTDecision[]
    ALTER TABLE public.mdt_meetings ADD COLUMN IF NOT EXISTS next_meeting_date TIMESTAMPTZ; -- nextMeetingDate: Date
    ALTER TABLE public.mdt_meetings ADD COLUMN IF NOT EXISTS created_by TEXT;      -- createdBy: string
  ELSE
    RAISE NOTICE 'skipped %: table not present', 'mdt_meetings';
  END IF;
END $$;

-- medication_charts  (7 columns)
DO $$
BEGIN
  IF to_regclass('public.medication_charts') IS NOT NULL THEN
    ALTER TABLE public.medication_charts ADD COLUMN IF NOT EXISTS total_scheduled NUMERIC; -- totalScheduled: number
    ALTER TABLE public.medication_charts ADD COLUMN IF NOT EXISTS total_administered NUMERIC; -- totalAdministered: number
    ALTER TABLE public.medication_charts ADD COLUMN IF NOT EXISTS compliance_rate NUMERIC; -- complianceRate: number
    ALTER TABLE public.medication_charts ADD COLUMN IF NOT EXISTS supervisor_review JSONB; -- supervisorReview: {
    ALTER TABLE public.medication_charts ADD COLUMN IF NOT EXISTS general_notes TEXT; -- generalNotes: string
    ALTER TABLE public.medication_charts ADD COLUMN IF NOT EXISTS handover_notes TEXT; -- handoverNotes: string
    ALTER TABLE public.medication_charts ADD COLUMN IF NOT EXISTS sync_status TEXT; -- syncStatus: 'pending' | 'synced' | 'error'
  ELSE
    RAISE NOTICE 'skipped %: table not present', 'medication_charts';
  END IF;
END $$;

-- meeting_minutes  (7 columns)
DO $$
BEGIN
  IF to_regclass('public.meeting_minutes') IS NOT NULL THEN
    ALTER TABLE public.meeting_minutes ADD COLUMN IF NOT EXISTS title TEXT;        -- title: string
    ALTER TABLE public.meeting_minutes ADD COLUMN IF NOT EXISTS location TEXT;     -- location: string
    ALTER TABLE public.meeting_minutes ADD COLUMN IF NOT EXISTS transcript JSONB;  -- transcript: MeetingTranscriptSegment[]
    ALTER TABLE public.meeting_minutes ADD COLUMN IF NOT EXISTS ai_summary TEXT;   -- aiSummary: string
    ALTER TABLE public.meeting_minutes ADD COLUMN IF NOT EXISTS has_recording BOOLEAN; -- hasRecording: boolean
    ALTER TABLE public.meeting_minutes ADD COLUMN IF NOT EXISTS status TEXT;       -- status: 'draft' | 'finalized' | 'shared'
    ALTER TABLE public.meeting_minutes ADD COLUMN IF NOT EXISTS created_by TEXT;   -- createdBy: string
  ELSE
    RAISE NOTICE 'skipped %: table not present', 'meeting_minutes';
  END IF;
END $$;

-- nurse_patient_assignments  (2 columns)
DO $$
BEGIN
  IF to_regclass('public.nurse_patient_assignments') IS NOT NULL THEN
    ALTER TABLE public.nurse_patient_assignments ADD COLUMN IF NOT EXISTS care_level TEXT; -- careLevel: 'routine' | 'intermediate' | 'intensive' | 'cr
    ALTER TABLE public.nurse_patient_assignments ADD COLUMN IF NOT EXISTS tasks JSONB; -- tasks: NursingTask[]
  ELSE
    RAISE NOTICE 'skipped %: table not present', 'nurse_patient_assignments';
  END IF;
END $$;

-- nutrition_assessments  (17 columns)
DO $$
BEGIN
  IF to_regclass('public.nutrition_assessments') IS NOT NULL THEN
    ALTER TABLE public.nutrition_assessments ADD COLUMN IF NOT EXISTS bmi_category TEXT; -- bmiCategory: string
    ALTER TABLE public.nutrition_assessments ADD COLUMN IF NOT EXISTS ideal_body_weight NUMERIC; -- idealBodyWeight: number
    ALTER TABLE public.nutrition_assessments ADD COLUMN IF NOT EXISTS adjusted_body_weight NUMERIC; -- adjustedBodyWeight: number
    ALTER TABLE public.nutrition_assessments ADD COLUMN IF NOT EXISTS status TEXT; -- status: NutritionStatus
    ALTER TABLE public.nutrition_assessments ADD COLUMN IF NOT EXISTS albumin NUMERIC; -- albumin: number
    ALTER TABLE public.nutrition_assessments ADD COLUMN IF NOT EXISTS prealbumin NUMERIC; -- prealbumin: number
    ALTER TABLE public.nutrition_assessments ADD COLUMN IF NOT EXISTS transferrin NUMERIC; -- transferrin: number
    ALTER TABLE public.nutrition_assessments ADD COLUMN IF NOT EXISTS hand_grip_strength NUMERIC; -- handGripStrength: number
    ALTER TABLE public.nutrition_assessments ADD COLUMN IF NOT EXISTS mid_arm_circumference NUMERIC; -- midArmCircumference: number
    ALTER TABLE public.nutrition_assessments ADD COLUMN IF NOT EXISTS triceps_skinfold NUMERIC; -- tricepsSkinfold: number
    ALTER TABLE public.nutrition_assessments ADD COLUMN IF NOT EXISTS appetite_level TEXT; -- appetiteLevel: 'good' | 'fair' | 'poor' | 'none'
    ALTER TABLE public.nutrition_assessments ADD COLUMN IF NOT EXISTS religious_dietary_needs TEXT; -- religiousDietaryNeeds: string
    ALTER TABLE public.nutrition_assessments ADD COLUMN IF NOT EXISTS current_feeding_route TEXT; -- currentFeedingRoute: FeedingRoute
    ALTER TABLE public.nutrition_assessments ADD COLUMN IF NOT EXISTS estimated_intake NUMERIC; -- estimatedIntake: number
    ALTER TABLE public.nutrition_assessments ADD COLUMN IF NOT EXISTS caloric_requirement NUMERIC; -- caloricRequirement: number
    ALTER TABLE public.nutrition_assessments ADD COLUMN IF NOT EXISTS protein_requirement NUMERIC; -- proteinRequirement: number
    ALTER TABLE public.nutrition_assessments ADD COLUMN IF NOT EXISTS fluid_requirement NUMERIC; -- fluidRequirement: number
  ELSE
    RAISE NOTICE 'skipped %: table not present', 'nutrition_assessments';
  END IF;
END $$;

-- payroll_periods  (2 columns)
DO $$
BEGIN
  IF to_regclass('public.payroll_periods') IS NOT NULL THEN
    ALTER TABLE public.payroll_periods ADD COLUMN IF NOT EXISTS total_billed NUMERIC; -- totalBilled: number
    ALTER TABLE public.payroll_periods ADD COLUMN IF NOT EXISTS closed_at TIMESTAMPTZ; -- closedAt: Date
  ELSE
    RAISE NOTICE 'skipped %: table not present', 'payroll_periods';
  END IF;
END $$;

-- payslips  (3 columns)
DO $$
BEGIN
  IF to_regclass('public.payslips') IS NOT NULL THEN
    ALTER TABLE public.payslips ADD COLUMN IF NOT EXISTS bank_name TEXT;           -- bankName: string
    ALTER TABLE public.payslips ADD COLUMN IF NOT EXISTS activities JSONB;         -- activities: {
    ALTER TABLE public.payslips ADD COLUMN IF NOT EXISTS pdf_generated BOOLEAN;    -- pdfGenerated: boolean
  ELSE
    RAISE NOTICE 'skipped %: table not present', 'payslips';
  END IF;
END $$;

-- post_op_lymphedema_monitoring  (25 columns)
DO $$
BEGIN
  IF to_regclass('public.post_op_lymphedema_monitoring') IS NOT NULL THEN
    ALTER TABLE public.post_op_lymphedema_monitoring ADD COLUMN IF NOT EXISTS surgical_procedure TEXT; -- surgicalProcedure: SurgicalProcedureType
    ALTER TABLE public.post_op_lymphedema_monitoring ADD COLUMN IF NOT EXISTS surgery_date TIMESTAMPTZ; -- surgeryDate: Date
    ALTER TABLE public.post_op_lymphedema_monitoring ADD COLUMN IF NOT EXISTS post_op_day NUMERIC; -- postOpDay: number
    ALTER TABLE public.post_op_lymphedema_monitoring ADD COLUMN IF NOT EXISTS monitored_at TIMESTAMPTZ; -- monitoredAt: Date
    ALTER TABLE public.post_op_lymphedema_monitoring ADD COLUMN IF NOT EXISTS monitored_by TEXT; -- monitoredBy: string
    ALTER TABLE public.post_op_lymphedema_monitoring ADD COLUMN IF NOT EXISTS wound_status TEXT; -- woundStatus: 'clean_dry' | 'serosanguinous' | 'infected' | 
    ALTER TABLE public.post_op_lymphedema_monitoring ADD COLUMN IF NOT EXISTS wound_details TEXT; -- woundDetails: string
    ALTER TABLE public.post_op_lymphedema_monitoring ADD COLUMN IF NOT EXISTS drain_output JSONB; -- drainOutput: { volumeMl: number
    ALTER TABLE public.post_op_lymphedema_monitoring ADD COLUMN IF NOT EXISTS limb_color TEXT; -- limbColor: 'normal' | 'pale' | 'cyanotic' | 'erythematous
    ALTER TABLE public.post_op_lymphedema_monitoring ADD COLUMN IF NOT EXISTS limb_temperature TEXT; -- limbTemperature: 'warm' | 'cool' | 'cold'
    ALTER TABLE public.post_op_lymphedema_monitoring ADD COLUMN IF NOT EXISTS capillary_refill_seconds NUMERIC; -- capillaryRefillSeconds: number
    ALTER TABLE public.post_op_lymphedema_monitoring ADD COLUMN IF NOT EXISTS pulse_status TEXT; -- pulseStatus: 'present_strong' | 'present_weak' | 'absent'
    ALTER TABLE public.post_op_lymphedema_monitoring ADD COLUMN IF NOT EXISTS sensation_intact BOOLEAN; -- sensationIntact: boolean
    ALTER TABLE public.post_op_lymphedema_monitoring ADD COLUMN IF NOT EXISTS compression_in_place BOOLEAN; -- compressionInPlace: boolean
    ALTER TABLE public.post_op_lymphedema_monitoring ADD COLUMN IF NOT EXISTS pain_score NUMERIC; -- painScore: number
    ALTER TABLE public.post_op_lymphedema_monitoring ADD COLUMN IF NOT EXISTS pain_management TEXT; -- painManagement: string
    ALTER TABLE public.post_op_lymphedema_monitoring ADD COLUMN IF NOT EXISTS temperature NUMERIC; -- temperature: number
    ALTER TABLE public.post_op_lymphedema_monitoring ADD COLUMN IF NOT EXISTS heart_rate NUMERIC; -- heartRate: number
    ALTER TABLE public.post_op_lymphedema_monitoring ADD COLUMN IF NOT EXISTS blood_pressure TEXT; -- bloodPressure: string
    ALTER TABLE public.post_op_lymphedema_monitoring ADD COLUMN IF NOT EXISTS complications JSONB; -- complications: string[]
    ALTER TABLE public.post_op_lymphedema_monitoring ADD COLUMN IF NOT EXISTS mobility_status TEXT; -- mobilityStatus: 'bed_rest' | 'bed_to_chair' | 'ambulating_assi
    ALTER TABLE public.post_op_lymphedema_monitoring ADD COLUMN IF NOT EXISTS dvt_prophylaxis TEXT; -- dvtProphylaxis: string
    ALTER TABLE public.post_op_lymphedema_monitoring ADD COLUMN IF NOT EXISTS notes TEXT; -- notes: string
    ALTER TABLE public.post_op_lymphedema_monitoring ADD COLUMN IF NOT EXISTS alerts JSONB; -- alerts: LymphedemaAlert[]
    ALTER TABLE public.post_op_lymphedema_monitoring ADD COLUMN IF NOT EXISTS created_at TIMESTAMPTZ; -- createdAt: Date
  ELSE
    RAISE NOTICE 'skipped %: table not present', 'post_op_lymphedema_monitoring';
  END IF;
END $$;

-- post_operative_notes  (13 columns)
DO $$
BEGIN
  IF to_regclass('public.post_operative_notes') IS NOT NULL THEN
    ALTER TABLE public.post_operative_notes ADD COLUMN IF NOT EXISTS who_checklist_completed BOOLEAN; -- whoChecklistCompleted: boolean
    ALTER TABLE public.post_operative_notes ADD COLUMN IF NOT EXISTS surgeon TEXT; -- surgeon: string
    ALTER TABLE public.post_operative_notes ADD COLUMN IF NOT EXISTS pre_operative_diagnosis TEXT; -- preOperativeDiagnosis: string
    ALTER TABLE public.post_operative_notes ADD COLUMN IF NOT EXISTS specimens_collected BOOLEAN; -- specimensCollected: boolean
    ALTER TABLE public.post_operative_notes ADD COLUMN IF NOT EXISTS vital_signs_frequency TEXT; -- vitalSignsFrequency: string
    ALTER TABLE public.post_operative_notes ADD COLUMN IF NOT EXISTS expected_recovery_days NUMERIC; -- expectedRecoveryDays: number
    ALTER TABLE public.post_operative_notes ADD COLUMN IF NOT EXISTS patient_education JSONB; -- patientEducation: PostOperativePatientEducation
    ALTER TABLE public.post_operative_notes ADD COLUMN IF NOT EXISTS follow_up_date TIMESTAMPTZ; -- followUpDate: Date
    ALTER TABLE public.post_operative_notes ADD COLUMN IF NOT EXISTS sutur_removal_date TIMESTAMPTZ; -- suturRemovalDate: Date
    ALTER TABLE public.post_operative_notes ADD COLUMN IF NOT EXISTS warning_signs JSONB; -- warningSigns: string[]
    ALTER TABLE public.post_operative_notes ADD COLUMN IF NOT EXISTS total_procedure_fee NUMERIC; -- totalProcedureFee: number
    ALTER TABLE public.post_operative_notes ADD COLUMN IF NOT EXISTS pdf_generated BOOLEAN; -- pdfGenerated: boolean
    ALTER TABLE public.post_operative_notes ADD COLUMN IF NOT EXISTS shared_via_whats_app BOOLEAN; -- sharedViaWhatsApp: boolean
  ELSE
    RAISE NOTICE 'skipped %: table not present', 'post_operative_notes';
  END IF;
END $$;

-- preoperative_assessments  (32 columns)
DO $$
BEGIN
  IF to_regclass('public.preoperative_assessments') IS NOT NULL THEN
    ALTER TABLE public.preoperative_assessments ADD COLUMN IF NOT EXISTS hospital_id TEXT; -- hospitalId: string
    ALTER TABLE public.preoperative_assessments ADD COLUMN IF NOT EXISTS created_by TEXT; -- createdBy: string
    ALTER TABLE public.preoperative_assessments ADD COLUMN IF NOT EXISTS created_at TIMESTAMPTZ; -- createdAt: Date
    ALTER TABLE public.preoperative_assessments ADD COLUMN IF NOT EXISTS status TEXT; -- status: 'draft' | 'pending_review' | 'approved' | 'req
    ALTER TABLE public.preoperative_assessments ADD COLUMN IF NOT EXISTS planned_procedure TEXT; -- plannedProcedure: string
    ALTER TABLE public.preoperative_assessments ADD COLUMN IF NOT EXISTS procedure_category TEXT; -- procedureCategory: ProcedureCategory
    ALTER TABLE public.preoperative_assessments ADD COLUMN IF NOT EXISTS planned_anaesthesia TEXT; -- plannedAnaesthesia: AnaesthesiaType
    ALTER TABLE public.preoperative_assessments ADD COLUMN IF NOT EXISTS surgical_urgency TEXT; -- surgicalUrgency: SurgicalUrgency
    ALTER TABLE public.preoperative_assessments ADD COLUMN IF NOT EXISTS planned_date TIMESTAMPTZ; -- plannedDate: Date
    ALTER TABLE public.preoperative_assessments ADD COLUMN IF NOT EXISTS surgeon_id TEXT; -- surgeonId: string
    ALTER TABLE public.preoperative_assessments ADD COLUMN IF NOT EXISTS asa_class TEXT; -- asaClass: ASAClass
    ALTER TABLE public.preoperative_assessments ADD COLUMN IF NOT EXISTS comorbidities JSONB; -- comorbidities: ComorbidityCategory[]
    ALTER TABLE public.preoperative_assessments ADD COLUMN IF NOT EXISTS clinical_notes TEXT; -- clinicalNotes: string
    ALTER TABLE public.preoperative_assessments ADD COLUMN IF NOT EXISTS airway_assessment JSONB; -- airwayAssessment: {
    ALTER TABLE public.preoperative_assessments ADD COLUMN IF NOT EXISTS functional_capacity JSONB; -- functionalCapacity: {
    ALTER TABLE public.preoperative_assessments ADD COLUMN IF NOT EXISTS required_investigations JSONB; -- requiredInvestigations: {
    ALTER TABLE public.preoperative_assessments ADD COLUMN IF NOT EXISTS optimization_plan JSONB; -- optimizationPlan: {
    ALTER TABLE public.preoperative_assessments ADD COLUMN IF NOT EXISTS anaesthetist_clearance JSONB; -- anaesthetistClearance: {
    ALTER TABLE public.preoperative_assessments ADD COLUMN IF NOT EXISTS fasting_instructions JSONB; -- fastingInstructions: {
    ALTER TABLE public.preoperative_assessments ADD COLUMN IF NOT EXISTS medication_instructions JSONB; -- medicationInstructions: {
    ALTER TABLE public.preoperative_assessments ADD COLUMN IF NOT EXISTS consent_obtained BOOLEAN; -- consentObtained: boolean
    ALTER TABLE public.preoperative_assessments ADD COLUMN IF NOT EXISTS consent_date TIMESTAMPTZ; -- consentDate: Date
    ALTER TABLE public.preoperative_assessments ADD COLUMN IF NOT EXISTS education_provided BOOLEAN; -- educationProvided: boolean
    ALTER TABLE public.preoperative_assessments ADD COLUMN IF NOT EXISTS education_procedure_id TEXT; -- educationProcedureId: string
    ALTER TABLE public.preoperative_assessments ADD COLUMN IF NOT EXISTS estimate_id TEXT; -- estimateId: string
    ALTER TABLE public.preoperative_assessments ADD COLUMN IF NOT EXISTS estimate_created BOOLEAN; -- estimateCreated: boolean
    ALTER TABLE public.preoperative_assessments ADD COLUMN IF NOT EXISTS surgery_name TEXT; -- surgeryName: string
    ALTER TABLE public.preoperative_assessments ADD COLUMN IF NOT EXISTS cardiac_risk JSONB; -- cardiacRisk: {
    ALTER TABLE public.preoperative_assessments ADD COLUMN IF NOT EXISTS vte_risk JSONB; -- vteRisk: {
    ALTER TABLE public.preoperative_assessments ADD COLUMN IF NOT EXISTS bleeding_risk JSONB; -- bleedingRisk: {
    ALTER TABLE public.preoperative_assessments ADD COLUMN IF NOT EXISTS assessed_by TEXT; -- assessedBy: string
    ALTER TABLE public.preoperative_assessments ADD COLUMN IF NOT EXISTS reviewed_by TEXT; -- reviewedBy: string
  ELSE
    RAISE NOTICE 'skipped %: table not present', 'preoperative_assessments';
  END IF;
END $$;

-- public_clinic_bookings  (8 columns)
DO $$
BEGIN
  IF to_regclass('public.public_clinic_bookings') IS NOT NULL THEN
    ALTER TABLE public.public_clinic_bookings ADD COLUMN IF NOT EXISTS full_name TEXT; -- fullName: string
    ALTER TABLE public.public_clinic_bookings ADD COLUMN IF NOT EXISTS hospital_code TEXT; -- hospitalCode: string
    ALTER TABLE public.public_clinic_bookings ADD COLUMN IF NOT EXISTS terms_accepted BOOLEAN; -- termsAccepted: boolean
    ALTER TABLE public.public_clinic_bookings ADD COLUMN IF NOT EXISTS status TEXT; -- status: 'confirmed' | 'checked_in' | 'completed' | 'no
    ALTER TABLE public.public_clinic_bookings ADD COLUMN IF NOT EXISTS confirmation_sent_at TIMESTAMPTZ; -- confirmationSentAt: Date
    ALTER TABLE public.public_clinic_bookings ADD COLUMN IF NOT EXISTS checked_in_at TIMESTAMPTZ; -- checkedInAt: Date
    ALTER TABLE public.public_clinic_bookings ADD COLUMN IF NOT EXISTS cancelled_at TIMESTAMPTZ; -- cancelledAt: Date
    ALTER TABLE public.public_clinic_bookings ADD COLUMN IF NOT EXISTS created_at TIMESTAMPTZ; -- createdAt: Date
  ELSE
    RAISE NOTICE 'skipped %: table not present', 'public_clinic_bookings';
  END IF;
END $$;

-- scanned_documents  (13 columns)
DO $$
BEGIN
  IF to_regclass('public.scanned_documents') IS NOT NULL THEN
    ALTER TABLE public.scanned_documents ADD COLUMN IF NOT EXISTS file_name TEXT;  -- fileName: string
    ALTER TABLE public.scanned_documents ADD COLUMN IF NOT EXISTS preview_url TEXT; -- previewUrl: string
    ALTER TABLE public.scanned_documents ADD COLUMN IF NOT EXISTS mime TEXT;       -- mime: string
    ALTER TABLE public.scanned_documents ADD COLUMN IF NOT EXISTS page_count NUMERIC; -- pageCount: number
    ALTER TABLE public.scanned_documents ADD COLUMN IF NOT EXISTS raw_text TEXT;   -- rawText: string
    ALTER TABLE public.scanned_documents ADD COLUMN IF NOT EXISTS mean_confidence NUMERIC; -- meanConfidence: number
    ALTER TABLE public.scanned_documents ADD COLUMN IF NOT EXISTS detected_modules JSONB; -- detectedModules: ModuleId[]
    ALTER TABLE public.scanned_documents ADD COLUMN IF NOT EXISTS added_at TEXT;   -- addedAt: string
    ALTER TABLE public.scanned_documents ADD COLUMN IF NOT EXISTS status TEXT;     -- status: 'queued' | 'ocr' | 'parsing' | 'done' | 'error
    ALTER TABLE public.scanned_documents ADD COLUMN IF NOT EXISTS error TEXT;      -- error: string
    ALTER TABLE public.scanned_documents ADD COLUMN IF NOT EXISTS words JSONB;     -- words: { text: string
    ALTER TABLE public.scanned_documents ADD COLUMN IF NOT EXISTS assisted_model TEXT; -- assistedModel: string
    ALTER TABLE public.scanned_documents ADD COLUMN IF NOT EXISTS pages JSONB;     -- pages: ScannedDocumentPage[]
  ELSE
    RAISE NOTICE 'skipped %: table not present', 'scanned_documents';
  END IF;
END $$;

-- skin_graft_records  (4 columns)
DO $$
BEGIN
  IF to_regclass('public.skin_graft_records') IS NOT NULL THEN
    ALTER TABLE public.skin_graft_records ADD COLUMN IF NOT EXISTS mesh_ratio TEXT; -- meshRatio: string
    ALTER TABLE public.skin_graft_records ADD COLUMN IF NOT EXISTS fixation_method TEXT; -- fixationMethod: 'sutures' | 'staples' | 'fibrin_glue' | 'negat
    ALTER TABLE public.skin_graft_records ADD COLUMN IF NOT EXISTS assessments JSONB; -- assessments: GraftAssessment[]
    ALTER TABLE public.skin_graft_records ADD COLUMN IF NOT EXISTS final_take_percentage NUMERIC; -- finalTakePercentage: number
  ELSE
    RAISE NOTICE 'skipped %: table not present', 'skin_graft_records';
  END IF;
END $$;

-- staff_patient_assignments  (1 column)
DO $$
BEGIN
  IF to_regclass('public.staff_patient_assignments') IS NOT NULL THEN
    ALTER TABLE public.staff_patient_assignments ADD COLUMN IF NOT EXISTS role TEXT; -- role: UserRole
  ELSE
    RAISE NOTICE 'skipped %: table not present', 'staff_patient_assignments';
  END IF;
END $$;

-- staff_payroll_records  (4 columns)
DO $$
BEGIN
  IF to_regclass('public.staff_payroll_records') IS NOT NULL THEN
    ALTER TABLE public.staff_payroll_records ADD COLUMN IF NOT EXISTS total_activities NUMERIC; -- totalActivities: number
    ALTER TABLE public.staff_payroll_records ADD COLUMN IF NOT EXISTS total_billed NUMERIC; -- totalBilled: number
    ALTER TABLE public.staff_payroll_records ADD COLUMN IF NOT EXISTS net_earnings NUMERIC; -- netEarnings: number
    ALTER TABLE public.staff_payroll_records ADD COLUMN IF NOT EXISTS activity_records JSONB; -- activityRecords: string[]
  ELSE
    RAISE NOTICE 'skipped %: table not present', 'staff_payroll_records';
  END IF;
END $$;

-- sti_assessments  (7 columns)
DO $$
BEGIN
  IF to_regclass('public.sti_assessments') IS NOT NULL THEN
    ALTER TABLE public.sti_assessments ADD COLUMN IF NOT EXISTS classification TEXT; -- classification: string
    ALTER TABLE public.sti_assessments ADD COLUMN IF NOT EXISTS clinical_features JSONB; -- clinicalFeatures: string[]
    ALTER TABLE public.sti_assessments ADD COLUMN IF NOT EXISTS comorbidities JSONB; -- comorbidities: {
    ALTER TABLE public.sti_assessments ADD COLUMN IF NOT EXISTS lrinec_score NUMERIC; -- lrinecScore: number
    ALTER TABLE public.sti_assessments ADD COLUMN IF NOT EXISTS generated_treatment_plan JSONB; -- generatedTreatmentPlan: {
    ALTER TABLE public.sti_assessments ADD COLUMN IF NOT EXISTS status TEXT;       -- status: 'draft' | 'active' | 'completed' | 'discharged
    ALTER TABLE public.sti_assessments ADD COLUMN IF NOT EXISTS assessed_by TEXT;  -- assessedBy: string
  ELSE
    RAISE NOTICE 'skipped %: table not present', 'sti_assessments';
  END IF;
END $$;

-- sti_debridement_records  (4 columns)
DO $$
BEGIN
  IF to_regclass('public.sti_debridement_records') IS NOT NULL THEN
    ALTER TABLE public.sti_debridement_records ADD COLUMN IF NOT EXISTS wound_dimensions JSONB; -- woundDimensions: { length: number
    ALTER TABLE public.sti_debridement_records ADD COLUMN IF NOT EXISTS is_culture_sent BOOLEAN; -- isCultureSent: boolean
    ALTER TABLE public.sti_debridement_records ADD COLUMN IF NOT EXISTS closure_method TEXT; -- closureMethod: 'open' | 'vac_therapy' | 'loose_packing' | 'de
    ALTER TABLE public.sti_debridement_records ADD COLUMN IF NOT EXISTS next_debridement_planned BOOLEAN; -- nextDebridementPlanned: boolean
  ELSE
    RAISE NOTICE 'skipped %: table not present', 'sti_debridement_records';
  END IF;
END $$;

-- substance_use_assessments  (6 columns)
DO $$
BEGIN
  IF to_regclass('public.substance_use_assessments') IS NOT NULL THEN
    ALTER TABLE public.substance_use_assessments ADD COLUMN IF NOT EXISTS withdrawal_risk_prediction JSONB; -- withdrawalRiskPrediction: WithdrawalRiskPrediction
    ALTER TABLE public.substance_use_assessments ADD COLUMN IF NOT EXISTS pain_management_support JSONB; -- painManagementSupport: PainManagementSupport
    ALTER TABLE public.substance_use_assessments ADD COLUMN IF NOT EXISTS relevant_comorbidities JSONB; -- relevantComorbidities: string[]
    ALTER TABLE public.substance_use_assessments ADD COLUMN IF NOT EXISTS clinician_override JSONB; -- clinicianOverride: {
    ALTER TABLE public.substance_use_assessments ADD COLUMN IF NOT EXISTS consent JSONB; -- consent: SubstanceUseConsent
    ALTER TABLE public.substance_use_assessments ADD COLUMN IF NOT EXISTS exclusion_criteria_flags JSONB; -- exclusionCriteriaFlags: {
  ELSE
    RAISE NOTICE 'skipped %: table not present', 'substance_use_assessments';
  END IF;
END $$;

-- substance_use_clinical_summaries  (2 columns)
DO $$
BEGIN
  IF to_regclass('public.substance_use_clinical_summaries') IS NOT NULL THEN
    ALTER TABLE public.substance_use_clinical_summaries ADD COLUMN IF NOT EXISTS patient_name TEXT; -- patientName: string
    ALTER TABLE public.substance_use_clinical_summaries ADD COLUMN IF NOT EXISTS addiction_score_summary JSONB; -- addictionScoreSummary: {
  ELSE
    RAISE NOTICE 'skipped %: table not present', 'substance_use_clinical_summaries';
  END IF;
END $$;

-- substance_use_consents  (8 columns)
DO $$
BEGIN
  IF to_regclass('public.substance_use_consents') IS NOT NULL THEN
    ALTER TABLE public.substance_use_consents ADD COLUMN IF NOT EXISTS diagnosis_explanation TEXT; -- diagnosisExplanation: string
    ALTER TABLE public.substance_use_consents ADD COLUMN IF NOT EXISTS detoxification_risks JSONB; -- detoxificationRisks: string[]
    ALTER TABLE public.substance_use_consents ADD COLUMN IF NOT EXISTS possible_withdrawal_effects JSONB; -- possibleWithdrawalEffects: string[]
    ALTER TABLE public.substance_use_consents ADD COLUMN IF NOT EXISTS pain_management_plan TEXT; -- painManagementPlan: string
    ALTER TABLE public.substance_use_consents ADD COLUMN IF NOT EXISTS monitoring_requirements JSONB; -- monitoringRequirements: string[]
    ALTER TABLE public.substance_use_consents ADD COLUMN IF NOT EXISTS patient_acknowledged BOOLEAN; -- patientAcknowledged: boolean
    ALTER TABLE public.substance_use_consents ADD COLUMN IF NOT EXISTS consent_device_info TEXT; -- consentDeviceInfo: string
    ALTER TABLE public.substance_use_consents ADD COLUMN IF NOT EXISTS document_version TEXT; -- documentVersion: string
  ELSE
    RAISE NOTICE 'skipped %: table not present', 'substance_use_consents';
  END IF;
END $$;

-- transfusion_monitoring_charts  (4 columns)
DO $$
BEGIN
  IF to_regclass('public.transfusion_monitoring_charts') IS NOT NULL THEN
    ALTER TABLE public.transfusion_monitoring_charts ADD COLUMN IF NOT EXISTS patient_name TEXT; -- patientName: string
    ALTER TABLE public.transfusion_monitoring_charts ADD COLUMN IF NOT EXISTS entries JSONB; -- entries: TransfusionMonitoringEntry[]
    ALTER TABLE public.transfusion_monitoring_charts ADD COLUMN IF NOT EXISTS total_volume_transfused NUMERIC; -- totalVolumeTransfused: number
    ALTER TABLE public.transfusion_monitoring_charts ADD COLUMN IF NOT EXISTS nurse_signature TEXT; -- nurseSignature: string
  ELSE
    RAISE NOTICE 'skipped %: table not present', 'transfusion_monitoring_charts';
  END IF;
END $$;

-- transfusion_orders  (7 columns)
DO $$
BEGIN
  IF to_regclass('public.transfusion_orders') IS NOT NULL THEN
    ALTER TABLE public.transfusion_orders ADD COLUMN IF NOT EXISTS patient_blood_group TEXT; -- patientBloodGroup: string
    ALTER TABLE public.transfusion_orders ADD COLUMN IF NOT EXISTS blood_bank_name TEXT; -- bloodBankName: string
    ALTER TABLE public.transfusion_orders ADD COLUMN IF NOT EXISTS screening_tests JSONB; -- screeningTests: TransfusionScreeningTests
    ALTER TABLE public.transfusion_orders ADD COLUMN IF NOT EXISTS rate_of_transfusion NUMERIC; -- rateOfTransfusion: number
    ALTER TABLE public.transfusion_orders ADD COLUMN IF NOT EXISTS pre_transfusion_vitals JSONB; -- preTransfusionVitals: {
    ALTER TABLE public.transfusion_orders ADD COLUMN IF NOT EXISTS consent_obtained BOOLEAN; -- consentObtained: boolean
    ALTER TABLE public.transfusion_orders ADD COLUMN IF NOT EXISTS ward_bed TEXT;  -- wardBed: string
  ELSE
    RAISE NOTICE 'skipped %: table not present', 'transfusion_orders';
  END IF;
END $$;

-- treatment_plans  (3 columns)
DO $$
BEGIN
  IF to_regclass('public.treatment_plans') IS NOT NULL THEN
    ALTER TABLE public.treatment_plans ADD COLUMN IF NOT EXISTS reminder_minutes_before JSONB; -- reminderMinutesBefore: number[]
    ALTER TABLE public.treatment_plans ADD COLUMN IF NOT EXISTS default_voice_note_id TEXT; -- defaultVoiceNoteId: string
    ALTER TABLE public.treatment_plans ADD COLUMN IF NOT EXISTS notification_preferences JSONB; -- notificationPreferences: {
  ELSE
    RAISE NOTICE 'skipped %: table not present', 'treatment_plans';
  END IF;
END $$;

-- user_settings  (5 columns)
DO $$
BEGIN
  IF to_regclass('public.user_settings') IS NOT NULL THEN
    ALTER TABLE public.user_settings ADD COLUMN IF NOT EXISTS email_notifications BOOLEAN; -- emailNotifications: boolean
    ALTER TABLE public.user_settings ADD COLUMN IF NOT EXISTS critical_alerts_only BOOLEAN; -- criticalAlertsOnly: boolean
    ALTER TABLE public.user_settings ADD COLUMN IF NOT EXISTS theme TEXT;          -- theme: 'light' | 'dark' | 'system'
    ALTER TABLE public.user_settings ADD COLUMN IF NOT EXISTS default_hospital_id TEXT; -- defaultHospitalId: string
    ALTER TABLE public.user_settings ADD COLUMN IF NOT EXISTS font_size TEXT;      -- fontSize: 'small' | 'medium' | 'large'
  ELSE
    RAISE NOTICE 'skipped %: table not present', 'user_settings';
  END IF;
END $$;

-- vital_signs  (1 column)
DO $$
BEGIN
  IF to_regclass('public.vital_signs') IS NOT NULL THEN
    ALTER TABLE public.vital_signs ADD COLUMN IF NOT EXISTS heart_rate NUMERIC;    -- heartRate: number
  ELSE
    RAISE NOTICE 'skipped %: table not present', 'vital_signs';
  END IF;
END $$;

-- wound_measurements  (6 columns)
DO $$
BEGIN
  IF to_regclass('public.wound_measurements') IS NOT NULL THEN
    ALTER TABLE public.wound_measurements ADD COLUMN IF NOT EXISTS calibration_method TEXT; -- calibrationMethod: 'qr_marker' | 'grid_sticker' | 'ruler' | 'coin
    ALTER TABLE public.wound_measurements ADD COLUMN IF NOT EXISTS length_cm NUMERIC; -- lengthCm: number
    ALTER TABLE public.wound_measurements ADD COLUMN IF NOT EXISTS granulation_percent NUMERIC; -- granulationPercent: number
    ALTER TABLE public.wound_measurements ADD COLUMN IF NOT EXISTS dominant_color TEXT; -- dominantColor: 'red' | 'yellow' | 'black' | 'pink' | 'mixed'
    ALTER TABLE public.wound_measurements ADD COLUMN IF NOT EXISTS segmentation_method TEXT; -- segmentationMethod: 'ai_auto' | 'ai_assisted' | 'manual_trace'
    ALTER TABLE public.wound_measurements ADD COLUMN IF NOT EXISTS measured_by TEXT; -- measuredBy: string
  ELSE
    RAISE NOTICE 'skipped %: table not present', 'wound_measurements';
  END IF;
END $$;

-- ---------------------------------------------------------------------------
-- 3. Pull-ordering indexes for the newly synced tables
-- ---------------------------------------------------------------------------

-- finance_buckets  (pull index)
DO $$
BEGIN
  IF to_regclass('public.finance_buckets') IS NOT NULL THEN
    CREATE INDEX IF NOT EXISTS idx_finance_buckets_updated_at ON public.finance_buckets(updated_at DESC);
  ELSE
    RAISE NOTICE 'skipped %: table not present', 'finance_buckets';
  END IF;
END $$;

-- finance_income  (pull index)
DO $$
BEGIN
  IF to_regclass('public.finance_income') IS NOT NULL THEN
    CREATE INDEX IF NOT EXISTS idx_finance_income_updated_at ON public.finance_income(updated_at DESC);
  ELSE
    RAISE NOTICE 'skipped %: table not present', 'finance_income';
  END IF;
END $$;

-- finance_transactions  (pull index)
DO $$
BEGIN
  IF to_regclass('public.finance_transactions') IS NOT NULL THEN
    CREATE INDEX IF NOT EXISTS idx_finance_transactions_updated_at ON public.finance_transactions(updated_at DESC);
  ELSE
    RAISE NOTICE 'skipped %: table not present', 'finance_transactions';
  END IF;
END $$;

-- finance_expenses  (pull index)
DO $$
BEGIN
  IF to_regclass('public.finance_expenses') IS NOT NULL THEN
    CREATE INDEX IF NOT EXISTS idx_finance_expenses_updated_at ON public.finance_expenses(updated_at DESC);
  ELSE
    RAISE NOTICE 'skipped %: table not present', 'finance_expenses';
  END IF;
END $$;

-- finance_projects  (pull index)
DO $$
BEGIN
  IF to_regclass('public.finance_projects') IS NOT NULL THEN
    CREATE INDEX IF NOT EXISTS idx_finance_projects_updated_at ON public.finance_projects(updated_at DESC);
  ELSE
    RAISE NOTICE 'skipped %: table not present', 'finance_projects';
  END IF;
END $$;

-- finance_investments  (pull index)
DO $$
BEGIN
  IF to_regclass('public.finance_investments') IS NOT NULL THEN
    CREATE INDEX IF NOT EXISTS idx_finance_investments_updated_at ON public.finance_investments(updated_at DESC);
  ELSE
    RAISE NOTICE 'skipped %: table not present', 'finance_investments';
  END IF;
END $$;

-- finance_audit_logs  (pull index)
DO $$
BEGIN
  IF to_regclass('public.finance_audit_logs') IS NOT NULL THEN
    CREATE INDEX IF NOT EXISTS idx_finance_audit_logs_updated_at ON public.finance_audit_logs(updated_at DESC);
  ELSE
    RAISE NOTICE 'skipped %: table not present', 'finance_audit_logs';
  END IF;
END $$;

-- sti_assessments  (pull index)
DO $$
BEGIN
  IF to_regclass('public.sti_assessments') IS NOT NULL THEN
    CREATE INDEX IF NOT EXISTS idx_sti_assessments_updated_at ON public.sti_assessments(updated_at DESC);
  ELSE
    RAISE NOTICE 'skipped %: table not present', 'sti_assessments';
  END IF;
END $$;

-- sti_debridement_records  (pull index)
DO $$
BEGIN
  IF to_regclass('public.sti_debridement_records') IS NOT NULL THEN
    CREATE INDEX IF NOT EXISTS idx_sti_debridement_records_updated_at ON public.sti_debridement_records(updated_at DESC);
  ELSE
    RAISE NOTICE 'skipped %: table not present', 'sti_debridement_records';
  END IF;
END $$;

-- lymphedema_assessments  (pull index)
DO $$
BEGIN
  IF to_regclass('public.lymphedema_assessments') IS NOT NULL THEN
    CREATE INDEX IF NOT EXISTS idx_lymphedema_assessments_updated_at ON public.lymphedema_assessments(updated_at DESC);
  ELSE
    RAISE NOTICE 'skipped %: table not present', 'lymphedema_assessments';
  END IF;
END $$;

-- lymphedema_monitoring_records  (pull index)
DO $$
BEGIN
  IF to_regclass('public.lymphedema_monitoring_records') IS NOT NULL THEN
    CREATE INDEX IF NOT EXISTS idx_lymphedema_monitoring_records_updated_at ON public.lymphedema_monitoring_records(updated_at DESC);
  ELSE
    RAISE NOTICE 'skipped %: table not present', 'lymphedema_monitoring_records';
  END IF;
END $$;

-- post_op_lymphedema_monitoring  (pull index)
DO $$
BEGIN
  IF to_regclass('public.post_op_lymphedema_monitoring') IS NOT NULL THEN
    CREATE INDEX IF NOT EXISTS idx_post_op_lymphedema_monitoring_updated_at ON public.post_op_lymphedema_monitoring(updated_at DESC);
  ELSE
    RAISE NOTICE 'skipped %: table not present', 'post_op_lymphedema_monitoring';
  END IF;
END $$;

-- wound_measurements  (pull index)
DO $$
BEGIN
  IF to_regclass('public.wound_measurements') IS NOT NULL THEN
    CREATE INDEX IF NOT EXISTS idx_wound_measurements_updated_at ON public.wound_measurements(updated_at DESC);
  ELSE
    RAISE NOTICE 'skipped %: table not present', 'wound_measurements';
  END IF;
END $$;

-- investigation_request_bundles  (pull index)
DO $$
BEGIN
  IF to_regclass('public.investigation_request_bundles') IS NOT NULL THEN
    CREATE INDEX IF NOT EXISTS idx_investigation_request_bundles_updated_at ON public.investigation_request_bundles(updated_at DESC);
  ELSE
    RAISE NOTICE 'skipped %: table not present', 'investigation_request_bundles';
  END IF;
END $$;
